### ISSUE TITLE
Show with Brendan Eich

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#1]
Would be super cool to get @BrendanEich on for the first show to kick us off and talk about the past and future of JavaScript.

Brendan, I sent you a direct message on twitter a few days ago and I'm waiting to hear back. Let me know what you think!

**Comment by kentcdodds** [comment]
This is going to be the first episode, and I'm super excited about it :-)

**Comment by PatrickJS** [comment]
:+1:
