### ISSUE TITLE
Unit Testing Javascript

### ISSUE THREAD

**Issue by ghost** [javascriptair/site#10]
**Title Idea:** Unit Testing Javascript

**Idea:** Discussion on current testing libraries, methodologies, and how to write good tests and good testable code

**Potential guest(s):** @joeeames, @wardbell

**Comment by kentcdodds** [comment]
Love it, would be cool to get @cjohansen (author of sinon.js) on as well!

**Comment by kentcdodds** [comment]
@joeeames, @wardbell, and @cjohansen, what do you think?

**Comment by joeeames** [comment]
Sounds fun

**Comment by wardbell** [comment]
Sounds fun to me!

Sent from my Windows Phone

**Comment by kentcdodds** [comment]
Awesome. @cjohansen, you're still invited, but why don't we get this scheduled!

Our next available slot is December 23rd. I realize that's two days before Christmas, but we're still going to have a show. If that doesn't work for you we can do December 30th. Shows are every Wednesday at 12:00 CST so we could do something next year as well.

What Wednesdays work for each of you in the next 4 weeks?

**Comment by wardbell** [comment]
Sorry but I cannot do Dec 23rd. On vacation. No computers allowed.

**Comment by kentcdodds** [comment]
That's fine. What Wednesdays are you available at 12:00 [CST](http://www.thetimezoneconverter.com/) in the next 4 weeks?

**Comment by cjohansen** [comment]
I'll join! I don't have specific plans, so I can fit it in.

**Comment by joeeames** [comment]
I may be traveling on the 30th. So that may not work for me. I can do the
next two wednesdays. Or any of the wednesdays in January.

On Fri, Dec 4, 2015 at 12:02 PM, Christian Johansen <
notifications@github.com> wrote:

> I'll join! I don't have specific plans, so I can fit it in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/javascriptair/site/issues/10#issuecomment-162053621.

## 

Joe Eames
Software Craftsman

**Comment by ghost** [comment]
Thanks Kent, Joe, Ward, and Christian for picking up this topic idea (and so quickly)!  I'm definitely looking forward to the show.  Hopefully others will find this topic to be as interesting and helpful as I do!

**Comment by kentcdodds** [comment]
How does Wednesday, January 6th, 2016 at 12:00 CST work for you @wardbell and @cjohansen?

**Comment by wardbell** [comment]
That’s 10am PST and it looks good for me.

**Comment by kentcdodds** [comment]
Sweet! So January 6th, 2016 at 12:00 CST it is! I'll get you each a calendar event. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information as you’d like it to appear on the site and description of the podcast (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name
- Your twitter handle
- A link to your Google+ profile
- Your profile picture at least 180x180px in size

Thanks!

**Comment by wardbell** [comment]
Ward Bell
@wardbell
Google+ profile: https://plus.google.com/u/0/117721243291907936009
![mr-lasvegas](https://cloud.githubusercontent.com/assets/129061/11602714/463f0990-9a91-11e5-95f8-8a1d455dd302.jpg)

**Comment by joeeames** [comment]
Joe Eames
@josepheames
https://plus.google.com/u/0/+JoeEames/
[image: Inline image 1]

On Fri, Dec 4, 2015 at 3:14 PM, Ward Bell notifications@github.com wrote:

> Ward Bell
> @wardbell https://github.com/wardbell
> Google+ profile: https://plus.google.com/u/0/117721243291907936009
> [image: mr-lasvegas]
> https://cloud.githubusercontent.com/assets/129061/11602714/463f0990-9a91-11e5-95f8-8a1d455dd302.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/javascriptair/site/issues/10#issuecomment-162097177.

## 

Joe Eames
Software Craftsman

**Comment by kentcdodds** [comment]
@joeeames, your image didn't come through.

**Comment by kentcdodds** [comment]
Forget it Joe, I'll just use your Twitter one :-) Thanks!

**Comment by joeeames** [comment]
https://dl.dropboxusercontent.com/u/39008480/KLP_0762-Square.jpg

On Fri, Dec 4, 2015 at 3:28 PM, Kent C. Dodds notifications@github.com
wrote:

> @joeeames https://github.com/joeeames, your image didn't come through.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/javascriptair/site/issues/10#issuecomment-162099791.

## 

Joe Eames
Software Craftsman

**Comment by cjohansen** [comment]
Is this the right time? http://www.timeanddate.com/worldclock/converted.html?iso=20160106T12&p1=155&p2=187

Name: Christian Johansen
Twitter handle: @cjno
Google+: I don't really have one - do I need one?
Profile pic: http://tddjs.com/images/christian-johansen.jpg

**Comment by kentcdodds** [comment]
That's the right time. The Google+ thing is just so I can +mention you on the Google+ Hangout on Air event. Not a really big deal. Thanks!

**Comment by kentcdodds** [comment]
The show has been scheduled and added to the site! https://github.com/javascriptair/site/commit/20d149efd42e28746c0b5e75e58fd78e4f6ed807

Looking forward to it!

**Comment by kentcdodds** [comment]
Sorry, I forgot I need one more thing from all of you. There will be a show google doc and I'll need an email to share that with you. Feel free to email me with that if you don't want to post it publicly here: [javascriptair@gmail.com](mailto:javascriptair@gmail.com)
