### ISSUE TITLE
Web Animations

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#106]
**Title:** Web Animations

**Description:** It's totally mind blowing what can be done to enhance the user's experience with animations on the web these days. Let's talk about how some of this is done and what tools are out there to help you with this.

**Potential guest(s):** @matsko

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by kentcdodds** [comment]
@matsko, if you have other ideas of guests to add to the show, that'd be great :-)

**Comment by pselle** [comment]
I wonder if @rachelnabors might be available!

**Comment by kentcdodds** [comment]
Would love to have you on the show @rachelnabors!

Also, would be awesome to have @sdras :+1:

**Comment by kentcdodds** [comment]
Oh, and by the way, I spoke with @matsko offline about this, but this show is scheduled for the 29th of June at 12:00 Central.

**Comment by nearestnabors** [comment]
Sure. Thanks for thinking of me, @pselle :)

Info:

I've been documenting the [Web Animations API on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) thanks to a Mozilla foundation grant and have made [many demos](http://codepen.io/collection/bpEza/) and give [this talk about it](https://vimeo.com/163510676).

I can also speak quite a bit as to how animation can be used with interfaces and to plus the user experience.

Founded this: slack.animationatwork.com
Curate this: http://webanimationweekly.com/

Rachel Nabors
rachelnabors@gmail.com
@rachelnabors

**Comment by sdras** [comment]
Hi! Thanks for pinging me.

I'd be happy to be on as well, if Rachel's cool with that :)

**Comment by nearestnabors** [comment]
I think Sarah is doing some great work with animation and can bring an
important perspective on the challenges of making animation a part of team
processes/design systems. Her presence can only improve the conversation :)

**Comment by kentcdodds** [comment]
Fantastic. I'll add @sdras to the show! Looking forward to chatting with you all on the 29th :D

**Comment by nearestnabors** [comment]
Me too! :)

[image: photo]
_Rachel Nabors_
Web Animation Engineer
w:rachelnabors.com
http://twitter.com/rachelnabors  http://dribbble.com/rachelthegreat
http://plus.google.com/u/0/+RachelNabors

## http://linkedin.com/in/rachelnabors

Curator of Web Animation Weekly http://webanimationweekly.com

_Speaking & Workshops_
- Aug 07 CSS Conf Argentina, Buenos Aires http://cssconfar.com/
- Oct 17 –18 CSS Dev Conf, San Antonio http://2016.cssdevconf.com/, Animation
  Workshop http://2016.cssdevconf.com/#workshops
- Oct 26 –27 All Things Open Keynote, Raleigh, NC
  http://allthingsopen.org/

**Comment by kentcdodds** [comment]
Added you already :-) https://javascriptair.com :-)
