### ISSUE TITLE
Automated Accessibility Testing with aXe-core

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#108]
**Title:** Automated Accessibility Testing with aXe-core

**Description:** The Deque Labs team is doing some really cool stuff for automated accessibility testing, bringing their years of accessibility expertise to mainstream web developers. The open source axe-core framework, written entirely in JavaScript, supports a bunch of integrations: Webdriver JS, Grunt and Gulp plugins, Chrome and Firefox extensions, and more. Get the low-down on how to integrate accessibility testing into your workflow with the core team from Deque. (pronounced Dee-Cue)

**Potential guest(s):** @marcysutton, @dylanb, @wilcofiers

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by dylanb** [comment]
I would definitely like to participate:

name: Dylan Barrell
email: dylan@barrell.com
twitter: @dylanbarrell

**Comment by kentcdodds** [comment]
@dylanb could you give me two or three days that work for you from [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md)?

**Comment by dylanb** [comment]
@kentcdodds 7/13 and 7/27

**Comment by marcysutton** [comment]
Yay! Those dates work for me too! 

I will email you my info.

**Comment by kentcdodds** [comment]
ping @wilcofiers, would you be interested in joining? If so, do 7/13 or 7/27 work for you?

**Comment by marcysutton** [comment]
Wilco said he could make 7/13 but not 7/27!

**Comment by kentcdodds** [comment]
Awesome! The 13th it is then!

**Comment by kentcdodds** [comment]
Really looking forward to this show! I need a few things from you all to get things set up for the show. I got this from @dylanb already. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by WilcoFiers** [comment]
Awesome! So here's my details:
Wilco Fiers, wilco.fiers@deque.com, @wilcofiers
