### ISSUE TITLE
For the Beginners

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#109]
**Title:** For the Beginners

**Description:** We're going to talk about when we were beginners, some of the things we wished we knew, some of our biggest early days goofs, our suggestions for newbies, etc. We'll also talk about making the community open to newbies/what can be done to increase this.

**Potential guest(s):** Open to suggestions!

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle
- Your profile picture at least 180x180px in size (or you can ask me to just use your github/twitter profile)

Thanks!

**Comment by sotojuan** [comment]
Might seem random but I'd like to see @mxstbr on this!

**Comment by mxstbr** [comment]
@sotojuan thanks for the recommendation.

Would love to talk about this!
My name is "Max Stoiber", my google mail is stoiber.maximilian (on gmail.com), my twitter handle is `@mxstbr` and you can find a picture here: http://mxstbr.com/headshot.jpeg

If you want me on the show, I'd prefer not to do it on the wednesday in two weeks but any other one within the next ~5 weeks works for me.

**Comment by kentcdodds** [comment]
I was actually planning on doing this show next week. Still need to hear from the panelists to hear who can make it.

**Comment by timdorr** [comment]
Happy to help with this as well.

**Comment by kentcdodds** [comment]
@timdorr, you're welcome to join! @mxstbr, you are as well if you can make it. Let me know and I'll update the website!

**Comment by mxstbr** [comment]
Let's do it!

**Comment by timdorr** [comment]
Yeah, add me to the list. BTW, I'd use timdorr@gmail.com for things, since that has a Google+ profile attached and will work best with Hangouts.

**Comment by kentcdodds** [comment]
Just added @mxstbr, @timdorr, and @Hendrixer to the show in addition to @AimeeKnight. I think this is going to be fantastic. See ya'll this Wednesday!

**Comment by sotojuan** [comment]
Woohoo 🎉
