### ISSUE TITLE
Routing in React

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#110]
**Title:** Routing in React

**Description:** react-router is a popular library for adding routing to your React apps. We'll look at what it means to add routing to an app and why you would want to do that. We'll also talk about some of the future of react-router and how we're looking to grow the library.

**Potential guest(s):** @timdorr, @ryanflorence, @mjackson, @taion

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by timdorr** [comment]
Sorry, the earliest available date for me is 2021, so you'll have to expand the schedule.

But seriously, I should be fine for most of the upcoming slots. I've got a kid on the way late next month, so if it gets pushed back that far for some reason, that might be the only conflict I have.

You can share things with timdorr@timdorr.com. I'm @timdorr on Twitter. And I'll give you one guess as to my real name for the site 😉

**Comment by kentcdodds** [comment]
Do ya'll think that next week would work? ping @ryanflorence, @mjackson, @taion

**Comment by taion** [comment]
I have a big work deadline coming up the week of the 20th. Next week would be really difficult for me.

**Comment by kentcdodds** [comment]
Ok, that's fine. How do the other dates look for you all?

**Comment by timdorr** [comment]
I'm good up until the 20th of next month. If you need something to fill next week's slot, I can help with #109 too.

**Comment by taion** [comment]
I'm good with further dates as well.

**Comment by sotojuan** [comment]
Can we have a 10 min segment where @taion teaches us how to make good coffee?

**Comment by kentcdodds** [comment]
ping @ryanflorence, @mjackson, do you guys wanna do this?

**Comment by mjackson** [comment]
Timing is bad since we're working on a total rewrite right now. We should
have something to start testing next week.

**Comment by kentcdodds** [comment]
Sure, how does the 3rd of August sound?

**Comment by kentcdodds** [comment]
Ok, so I think we should chat about React Router v4 :) How are these dates?
- 5 Oct
- 12 Oct

Remember, the show is at 12:00 CT

**Comment by kentcdodds** [comment]
ping @ryanflorence
I'd be happy to have up to 4 guests on the show :)

**Comment by timdorr** [comment]
I'm free on both days (Wednesday, btw).

**Comment by kentcdodds** [comment]
ping @ryanflorence, @mjackson, and @taion.

**Comment by taion** [comment]
I'm not using React Router v4 and don't plan on doing so. I could discuss the situations in which RRv4 may or may not be appropriate for a project, but the set of projects for which RRv4 is not an ideal fit is likely restricted to a more advanced subset, so it may not be of general interest.

**Comment by kentcdodds** [comment]
Sorry it's taken so long for me to respond. If you're still good to go @timdorr and @taion, let's do this. It'd be great to get both of your perspectives on the show (that's part of what makes JavaScript Air unique/great IMO).

Can you both still make it this Wednesday at 12:00 CT?

**Comment by timdorr** [comment]
I'm still good. No worries on the timing. I know you're a super-busy dude!

**Comment by taion** [comment]
That time works for me.

**Comment by kentcdodds** [comment]
Alright. It's added to the schedule. @taion, what's your email address? I need to share a Google Doc with both of you.

**Comment by taion** [comment]
I sent you an email.

**Comment by kentcdodds** [comment]
Hey guys, we decided to actually cover this show on React30 instead. Sorry about that!
