### ISSUE TITLE
Getting started with web audio

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#111]
**Title:** Getting started with web audio

**Description:** Web audio opens the door for rich multimedia, audio and gaming applications. It remains an unknown topic for many. Let's get an overview at audio programming with JavaScript and an introduction to some tools and frameworks that can make your life easier doing this.

**Potential guest(s):** @chrislo, @alemangui, @titusblair, @tencircles

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by chrislo** [comment]
I'd be interested to take part, I think the broadcast happens at a good time for me (London, UK)! 

Name: Chris Lowis
Twitter: @chrislowis

**Comment by chrislo** [comment]
I think the first two available dates I can make are:
- 2016-07-20
- 2016-07-27

**Comment by alemangui** [comment]
Also interested in participating :) 

Name: Alejandro Mantecon Guillen
Twitter: @alemangui

Any date in July works for me

**Comment by tencircles** [comment]
I'm interested, free in July. 

Name: Chris Coniglio
Twitter: @tencircles
Email: chris@dinahmoe.com

**Comment by kentcdodds** [comment]
@alemangui, what's your email address?

**Comment by alemangui** [comment]
@kentcdodds it's alemangui@gmail.com
