### ISSUE TITLE
Electron apps

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#112]
**Title:** Electron apps

**Description:** Electron is becoming more and more of a relevant and popular way of building multi-platform desktop apps with web technologies. Let's get a dive into this awesome tech and see how we can use it to enhance our own experience and our user's experience on the desktop.

**Potential guest(s):** @emorikawa (anyone else you'd recommend)?

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by kentcdodds** [comment]
Going to ping the top 4 committers to the Electron project here. Would ya'll be interested in coming on to talk about Electron on [JavaScript Air](https://javascriptair.com)? See [above](https://github.com/javascriptair/site/issues/112#issue-158979089) for more info :-)

@zcbenz, @kevinsawicki, @deepak1556, @preco21

**Comment by kevinsawicki** [comment]
> Would ya'll be interested in coming on to talk about Electron on JavaScript Air? See above for more info :-)

Thanks for reaching out, but being on a podcast sounds terrifying 😰

**Comment by kentcdodds** [comment]
@kevinsawicki 

> being on a podcast sounds terrifying 😰

I understand and respect that some people are more comfortable with it than others. Hopefully it will comfort you to know that we've had [a lot of people](https://javascriptair.com/guests/) on the show and some of them are more comfortable doing this kind of thing than others. But the common thread that I've seen with everyone coming on the show is the experience is a very positive one. We have a lot of fun just chatting away about tech that we think is cool and interesting. And, for what it's worth, we do have a great [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) that I've luckily never really had to enforce because everyone abides by it.

I'd love to have you on the show. Let me know what I can do to make things more comfortable for you :-)

**Comment by jlord** [comment]
@kentcdodds 👋 I'm on the Electron team at GitHub with @kevinsawicki and would be happy to join in his place if that works for you (he gave his blessing 😀).

**Comment by kentcdodds** [comment]
@jlord that'd be fantastic. Thank you for stepping in! Could let me know a few dates available on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md) that work for you?

**Comment by preco21** [comment]
@kentcdodds Thank you for inviting me. :smile: But since I can't speak English as well, so I think I'd just better to watch the screencast. Cheers!

**Comment by kentcdodds** [comment]
Understood @preco21! Thanks for your work on Electron!

**Comment by emorikawa** [comment]
Yes! This sounds like an awesome idea

**Comment by kentcdodds** [comment]
Great @emorikawa! @jlord and @emorikawa, what dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md) work for you? Any chance ya'll could do this next Wednesday? The show airs at 12:00 Central Time. If not, what other dates work? Also @zcbenz and @deepak1556, would you be interested in coming on as well?

**Comment by emorikawa** [comment]
Wed 6/15 works for me. I'm also available. 7/6  

Sent from [Nylas N1](https://link-
staging.nylas.com/link/5hz5culosbij8sy0d4j7vuf2r/local-
4fb4c686-77cd/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1), the
extensible, open source mail client.  
![](https://link-staging.nylas.com/open/5hz5culosbij8sy0d4j7vuf2r/local-
4fb4c686-77cd)

**Comment by jlord** [comment]
📆 7/6 would be best for me.

**Comment by deepak1556** [comment]
Thanks for the invite, 7/6 works for me.

**Comment by kentcdodds** [comment]
Thanks @jlord, @deepak1556, and @emorikawa. Let's plan on 7/6 then! @zcbenz, you're still invited if you're interested :-)

**Comment by kentcdodds** [comment]
@deepak1556, what's your twitter handle? I need it to add you to the website :-)
