### ISSUE TITLE
Publishing JavaScript Packages

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#113]
**Title:** Publishing JavaScript Packages

**Description:** How to automate the workflow of git tags, changelog, npm publish and how the developing/publishing workflow could be improved.

**Potential guest(s):** @substack, @sindresorhus, @jdalton, @boennemann

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by jdalton** [comment]
Count me in 💯

**Comment by boennemann** [comment]
Hey @kentcdodds,

thanks for the invitation. Would love to join.
I'm on vacation next week, but the other open dates seem fine.
- Stephan Bönnemann
- stephan.boennemann at gmail.com
- @boennemann

Good luck with today's show!

**Comment by sotojuan** [comment]
What about the Lerna people? @thejameskyle @hzoo @kittens, though some have been on the show already. They got an interesting way to do package publishing.

**Comment by kentcdodds** [comment]
Fantastic idea @sotojuan! What do you say guys?

**Comment by jamiebuilds** [comment]
Sure, happy to do it

**Comment by jamiebuilds** [comment]
James Kyle
me@thejameskyle.com
@thejameskyle

**Comment by jamiebuilds** [comment]
These work for me: 2016-07-20, 2016-08-03, 2016-08-10, 2016-08-17

**Comment by hzoo** [comment]
If you can fit another, sure

Henry Zhu
hi@henryzoo.com
`@left_pad`

**Comment by kentcdodds** [comment]
@hzoo, how could we leave out `@left_pad`? Happy to have you join!
