### ISSUE TITLE
Typed FP in JS

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#114]
**Title:** Typed Functional Programming in JavaScript

**Description:** "Tie your hands to free your mind" is a mantra you hear that applies really well to the constraints that you put on yourself by embracing statically typed languages and functional programming. We're going to hear from various people about their respective visions of typed FP in JS.

**Potential guest(s):** @paf31, @evancz, @jordwalke, @alfonsogarciacaro

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by alfonsogarciacaro** [comment]
This is a fantastic idea and I'll love to join! Please find my info below. Do you also need a bio?
- Name: Alfonso García-Caro
- Mail: alfonso.garcia-caro (at) hotmail.com (yeah, still using hotmail, too lazy to change it)
- Twitter: @alfonsogcnunez
- Project: [Fable](http://fsprojects.github.io/Fable/), F# to JS compiler

Next Wednesday (June 15th) I'll be out of town so I'm not sure about the internet conditions, but any of the July dates should be fine for me 👍

**Comment by kentcdodds** [comment]
> Do you also need a bio?

Nope, this will work for me. Thanks!

**Comment by pselle** [comment]
This sounds like maybe a @bodil topic. I, in general, would adore having @bodil on the show.

**Comment by texastoland** [comment]
@rtfeldman ping @evancz?

**Comment by kentcdodds** [comment]
Yes! @bodil, would you like to jump on with us? I've actually been meaning to invite you on the show for a while now anyway :D would love to have you on.

**Comment by ttbodil** [comment]
Not me, podcasts are really not my medium. But please make @paf31 do it. :)

**Comment by bodil** [comment]
Not me, podcasts are really not my medium. But please make @paf31 do it. :)

**Comment by kentcdodds** [comment]
Understood. You will be missed @bodil. Thanks anyway!

**Comment by evancz** [comment]
Sounds cool, but you should have @rtfeldman on instead of me. He introduced it at NoRedInk about a year ago, and they are now the biggest user in the world as far as I know. So in addition to knowing a ton about Elm itself (like me), he probably knows more than anyone about the day-to-day usage and team dynamics of introducing a technology like this. In other words, I think he'd be a better choice!

**Comment by kentcdodds** [comment]
Alright, what do you think @rtfeldman?

**Comment by rtfeldman** [comment]
Happy to! Sounds like a fun one. 😄 
- Richard Feldman
- richard.t.feldman@gmail.com
- [@rtfeldman](https://twitter.com/rtfeldman)

**Comment by kentcdodds** [comment]
@rtfeldman can you give me a few dates from [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md) that work well for you at 12:00 Central Time?

**Comment by rtfeldman** [comment]
@kentcdodds any from 7/20 to 8/31 (7/20, 7/27, 8/3, 8/10, 8/17, 8/24, 8/31) are fine

**Comment by bookercodes** [comment]
This is going to be awesome :tada:

**Comment by texastoland** [comment]
@paf31 ping!

**Comment by jordwalke** [comment]
This sounds fun. I can't commit to anything for a little while, but can we check back on this in about one week?

**Comment by kentcdodds** [comment]
Sure thing Jordan. You'll hear from me in a week

**Comment by paf31** [comment]
Sounds fun, sign me up! I probably won't be able to make the dates in July from Richard's list, but the ones in August (i.e 8/3, 8/10, 8/17, 8/24, 8/31) should be fine.
- Phil Freeman
- <my-github-username>@cantab.net
- [@paf31](http://twitter.com/paf31)

**Comment by kentcdodds** [comment]
Ping @jordwalke.

**Comment by kentcdodds** [comment]
FYI everyone, it's looking like the show will probably be on 8/03 or 8/17. Let me know if that doesn't work well for anyone. (Still waiting for what @jordwalke has to say)

**Comment by alfonsogarciacaro** [comment]
That should work for me :+1:

**Comment by rtfeldman** [comment]
Either sounds good!

**Comment by kentcdodds** [comment]
Ok, let's plan on 8/03. @jordwalke, you're still invited. I hope you can come. I enjoyed our chat on React30 and would love to chat with you again on JavaScript Air 😄  (format is similar).

**Comment by jordwalke** [comment]
I'll see if I can make it (what time of day?). Thanks!

**Comment by rtfeldman** [comment]
Sounds good! @kentcdodds can you [DM me on Twitter](https://twitter.com/rtfeldman) with info on how to join the call?

**Comment by kentcdodds** [comment]
You'll all get an invite to a Google doc soon. More info will be in there. Thanks!

**Comment by kentcdodds** [comment]
Alrighty! The show is on the website now (with your avatars and names, please double check that it looks ok). You should have received an email inviting you to a Google Doc. If you didn't, let me know.

As always, let me know if you have any questions 😄  Looking forward to the show!

Oh, and @jordwalke, the show is at 10:00 AM PT.
