### ISSUE TITLE
How to be a mentor

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#117]
**Title:** How to be a mentor

**Description:** With so many new developers coming into the JavaScript world, there's never been a greater need for experienced developers to mentor and teach others. In this episode we'll chat with some experts on how to be an effective mentor.

**Potential guest(s):** @kmcrayton7, @taras, @mainroach, @JedWatson

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by taras** [comment]
I'm in interested in participating in one of these episodes.

Name: Taras Mankovski
Email: taras@embersherpa.com
Twitter: EmberSherpa

I'm available anytime starting August 10th.

**Comment by kmcrayton7** [comment]
I'm interested:

Kim Crayton
Kim@KimCrayton.com
KimCrayton1 and JrDevMentoring
I make my own schedule so my availability is flexible

**Comment by mainroach** [comment]
Interested.
Colt McAnlis, @duhroach (NOT @mainroach)
duhroach@gmail.com
Available in August

**Comment by JedWatson** [comment]
I'm in! Need to confirm some travel dates (family holiday to China mid-august, so connectivity may/will be an issue) but will get back to you asap :)

Jed Watson
@jedwatson on twitter

**Comment by kentcdodds** [comment]
@JedWatson, I've added the show to the schedule. Let me know if the date I chose doesn't work and we can move it :-)

**Comment by kentcdodds** [comment]
Alrighty! The show is on the website now (with your avatars and names, please double check that it looks ok). You should have received an email inviting you to a Google Doc. If you didn't, let me know.

As always, let me know if you have any questions 😄  Looking forward to the show!

**Comment by timdorr** [comment]
As a follow-up, can we get a "How to be a mentee" episode? :smile: I think that's an equally valuable skill worth exploring.
