### ISSUE TITLE
Microsoft Open Sourced Chakra

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#12]
**Title Idea:** Chakra, Microsoft's JS Engine

**Idea:** At JSConf this morning, Gaurav Seth & Steve Lucco announced that Microsoft will be open sourcing Chakra. I know that many developers will be even more interested than ever to find out about what this is and what it means for JavaScript developers.

**Potential guest(s):** @steveluc, @gauravseth

**Comment by oaleynik** [comment]
Yes, please :+1: Thanks @kentcdodds

**Comment by e-oz** [comment]
+1

**Comment by kentcdodds** [comment]
Seems like @jdalton knows a thing or two about Chakra as well. John, do you want to come on the show to talk about this as well?

**Comment by tikotzky** [comment]
Big +1 from me :)

**Comment by PatrickJS** [comment]
:+1:

**Comment by jdalton** [comment]
Can dig, will see.

**Comment by kentcdodds** [comment]
Well, one way or another @jdalton, I'd really love to have you on the show :-)

**Comment by jdalton** [comment]
Sure, hit me up anytime :D

**Comment by learningjs** [comment]
+1 +1 +1

**Comment by kentcdodds** [comment]
@jdalton, @steveluc, @gauravseth, how does the 27th of January 2016 sound?

**Comment by kentcdodds** [comment]
Oh, also, @jdalton, @steveluc, @gauravseth, if you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by sethgaurav** [comment]
:+1:

**Comment by kentcdodds** [comment]
Confirmed with @gauravseth and I think the 27th will work. Really looking forward to this show! I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information as you’d like it to appear on the site and description of the podcast (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name
- An email address to share a Google Doc with you
- Your twitter handle
- A link to your Google+ profile
- Your profile picture at least 180x180px in size

Thanks!

**Comment by kentcdodds** [comment]
Alrighty, this show is ready to go. @steveluc and @jdalton, please let me know if you'll be able to attend and I'll get you on the docket as well (I'd really love to have both of you).

@sethgaurav, you should have received an email with a Google Doc. Let me know if you have any questions! RSVP to [this event](https://plus.google.com/events/cr1d6qpgnbgn5a77upg4hu010gk) to get it added to your calendar.
