### ISSUE TITLE
Add GitHub link to javascriptair.com

### ISSUE THREAD

**Issue by bookercodes** [javascriptair/site#123]
[javascriptair/site](https://github.com/javascriptair/site) isn't mentioned on [javascriptair.com](https://javascriptair.com/). 

At the very least, I think it should be added to the footer :+1: 

I hope that doing so will draw some new contributors. 

Whaddaya think?

**Comment by kentcdodds** [comment]
Agreed. We should also add a link to the contributors page to the footer. Right now it's in the sponsors section which is fine, but I think it should be in the footer too

**Comment by vesparny** [comment]
something like that?

![image](https://cloud.githubusercontent.com/assets/82070/16120657/8dfbc4c4-33e0-11e6-9a97-5e20d4beb6dd.png)

**Comment by kentcdodds** [comment]
LGTM. We should eventually think about redesigning that footer slightly to accommodate so many links.

**Comment by housseindjirdeh** [comment]
Hmm or link to the contributors there and have the the github link on the left hand side?
![capture](https://cloud.githubusercontent.com/assets/12476932/16120797/d6b4afc8-33ae-11e6-9567-ecdfff9519e7.PNG)

**Comment by bookercodes** [comment]
@kentcdodds I agree. We could just make the list vertical?

![](http://i.imgur.com/GP70Wnb.png)

**Comment by kentcdodds** [comment]
Oh yeah, if we could add a GitHub svg on the left side that'd be good too. Just thought we should probably link to the code of conduct there too. 

https://github.com/javascriptair/CODE_OF_CONDUCT

**Comment by bookercodes** [comment]
@kentcdodds Sounds perfect :+1:

**Comment by kentcdodds** [comment]
> We could just make the list vertical

Sounds good to me. Maybe we could have it be three columns so it's not so tall. We'd want it to be responsive for mobile though. For anyone wanting to work on it, the code is around [here](https://github.com/javascriptair/site/blob/60e577a700b5e03ecf50b6802e87bf2c2fdd7553/src/pages/home/sections/footer/footer.js). We don't have a grid system, but you can use bootstrap :-)

**Comment by housseindjirdeh** [comment]
I'll get to this later today/tomorrow. However if someone wants to work on it earlier then that feel free :+1:

**Comment by housseindjirdeh** [comment]
Let me know what you guys think, two columns look pretty decent:
![laptop](https://cloud.githubusercontent.com/assets/12476932/16135717/7edd7682-33f3-11e6-80b9-d5b3e6806176.PNG)

**Comment by housseindjirdeh** [comment]
Resizes to mobile:
![mobile](https://cloud.githubusercontent.com/assets/12476932/16135896/87a75728-33f4-11e6-9ed7-b1f9d90ef39e.PNG)

Resizes to small tablet:
![tablet](https://cloud.githubusercontent.com/assets/12476932/16135899/8adcbaaa-33f4-11e6-9fb2-69313ab47870.PNG)

**Comment by kentcdodds** [comment]
Yes! That looks fantastic!

**Comment by housseindjirdeh** [comment]
Okay awesome :) Will get a PR in tomorrow morning
