### ISSUE TITLE
Throttle processes on builds

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#127]
Right now, we spawn a TON of processes during the build. One for every page (including each episode page). This is not the greatest situation and it's finally [bitten us](https://travis-ci.org/javascriptair/site/builds/138154325):

<img width="1141" alt="screen shot 2016-06-16 at 11 57 26 am" src="https://cloud.githubusercontent.com/assets/1500684/16127391/86dca39c-33b9-11e6-9a5f-71175365cd44.png">

I want to keep _some_ parallelism (because otherwise this will take forever), but we need to throttle it. The code that should be updated is [here](https://github.com/javascriptair/site/blob/ef7df6b222526f3dc1d72037301e1a7c26d06a5b/scripts/build-episodes.sh). We somehow need to make that throttle the number of concurrent scripts being run. I need a bash expert or someone who can convert this to a node program that will run these in parallel. I'm fine with either solution. I'm thinking if we do 10 at a time we should be good.

Help appreciated!

**Comment by kentcdodds** [comment]
Note: This is a bit of a high priority because the site is broken and I can't deploy the fix until this is resolved. Hopefully I can get to it soon, but if anyone wants to give me some tips on how I can do the throttling, I'd appreciate it!

**Comment by joshmanders** [comment]
This seems way over engineered and could be the issue.. Is there a reason you're not using something like gulp, which could handle all this in a better fashion?

I've done similar to what you are doing for building episodes, but instead of a JS object I used a markdown with frontmatter in it to do stuff, and I built hundreds of pages pretty quickly using gulp.

Edit: example

https://github.com/joshmanders/node-by-example/blob/master/gulpfile.js

**Comment by kentcdodds** [comment]
I disagree that this is over engineered. I think what you see as over engineering is actually just an issue of familiarity. I'd love to see an example of how I could make this better with gulp, but I'm skeptical that it would make things simpler.

**Comment by joshmanders** [comment]
You're correct, over engineering was the wrong term, I am not familiar with the package-scripts thing you're using.

In my example gulpfile what I am doing is passing a glob of `.md` files to a through stream to first check the contents for a first level heading in markdown to assign to a title property on the file object. After that I pass it through frontmatter parser to take out all the frontmatter of the markdown file and put that on a `meta` prop on the file object. Then run it through markdown parser before coming back through another through stream that allows me to compile a jade template with locals from the `meta` prop, and generate a table of contents to inject into the template, before rendering each markdown file as a html file of it's own with the template and table of contents in it.

It takes [this file](https://raw.githubusercontent.com/joshmanders/node-by-example/master/src/hello-world.md) and converts it into [this page](http://www.nodebyexample.com/hello-world/) by merging [these](https://raw.githubusercontent.com/joshmanders/node-by-example/master/src/template.jade) [two](https://raw.githubusercontent.com/joshmanders/node-by-example/master/src/toc.md) files together.

**Comment by timarney** [comment]
For context might help to point people here https://github.com/javascriptair/site/tree/master/scripts (at least as a starting point)

Episodes 

```
for D in `ls -d episodes/*/`
do
  ./scripts/build-episode.sh $D &
done

wait
echo "episodes built 😎"
```

**Comment by kentcdodds** [comment]
I'm working on a solution right now that I think will be good.

**Comment by thangngoc89** [comment]
@kentcdodds @Phenomic_app used to have a script that spawn AVA's processes in parallelism to avoid this kind of error
https://github.com/MoOx/phenomic/blob/2f08239d804fc3e1ad69151127f3d76466713047/scripts/ava-serial.js#L31

**Comment by ryanbraganza** [comment]
This [stackoverflow answer](http://unix.stackexchange.com/a/216475/13281) looks like it should be easily adaptable to your code.

``` bash
N=4
(
for thing in a b c d e f g; do 
   ((i=i%N)); ((i++==0)) && wait
   task "$thing" & 
done
)
```

Something like..

``` bash
CONCURRENCY=10

for D in `ls -d episodes/*/`
do
  ((i=i%CONCURRENCY)); ((i++==0)) && wait
  ./scripts/build-episode.sh $D &
done

wait
echo "episodes built 😎"

```

In general, I would recommend using something like [GNU Parallel](http://www.gnu.org/software/parallel/) for things like this.

**Comment by kentcdodds** [comment]
Thanks everyone for weighing in with good ideas and helpful information. [Here's how I solved it](https://github.com/javascriptair/site/commit/c3ebf05a02384007e3161d91ef1bbc31c616f61b):

Basically now the `build-episode.sh` and `build-episodes.sh` scripts are node scripts now. The `build-episodes.js` uses the [`async`](http://npm.im/async) package to iterate through each of the episodes and build them.

A benefit of this approach (as opposed to bash) is that now I only run `babel-node` once, which means that all the modules are transpiled only once (rather than for every episode). I always knew that running `babel-node` for each one was the main reason for the slowness, but I didn't expect it to take this part of my build from 1 minute 34 seconds to 32 seconds!!! (this includes building all other pages). Pretty crazy stuff.

Thanks again for the tips and help.
