### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#13]
**Title Idea:** ESLint

**Idea:** Let's talk about what ESLint is, how it works, and how it's useful

**Potential guest(s):** @nzakas, @gyandeeps, @xjamundx

**Comment by kentcdodds** [comment]
Let me know if you're interested in doing this show @nzakas, @gyandeeps, and @xjamundx!

**Comment by nzakas** [comment]
I'm not well enough to be doing interviews at this point, but maybe the other folks are interested.

**Comment by kentcdodds** [comment]
I've heard that you're health's not been very good @nzakas. You've done amazing things for the community (not just ESLint). Thank you for your contributions. Get well soon man!

**Comment by xjamundx** [comment]
Totally willing to help out @kentcdodds. I love `eslint` though I haven't contributed as much lately :open_mouth: 

Also @ianvs and @ilyavolodin or @btmills or @lo1tuma and the rest of the contributors all might be great. 

But also I really like https://github.com/feross/standard, so I'd love to have you talk to @feross either on the same panel or a different one. Standard is built on top of ESLint, but it's a different philosophy (less config, etc) and I think might make for a nice discussion about linting in general.

**Comment by hzoo** [comment]
I can be of assistance as well babel-eslint, jscs, etc.

**Comment by xjamundx** [comment]
:+1: for @hzoo he has a lot of experience working on both jscs and eslint!

**Comment by kentcdodds** [comment]
I think we could definitely have @feross on to talk about standard on this show. We've got an hour so hopefully that'll be enough to cover everything :-) What do you think @feross?

Anyone else up for joining this show?

**Comment by gyandeeps** [comment]
I can join too.
@kentcdodds What date/time are we talking about because end of December I might be travelling?

**Comment by kentcdodds** [comment]
Great question... Here's the usual blurb :-) 

If you haven't heard of [JavaScript Air](http://javascriptair.com/) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by ilyavolodin** [comment]
If needed I can join. December 30th would work for me.

**Comment by hzoo** [comment]
Dec 30 sounds good

**Comment by xjamundx** [comment]
30th is my anniversary :) Happy to let some other eslint voices handle this one. Let me know if you can't get enough folks and I can help on another.

**Comment by kentcdodds** [comment]
@gyandeeps how's the 30th for you?

**Comment by gyandeeps** [comment]
Yikes, I will be traveling on 30th. Any thing available for January?
I am interested to join this podcast.

**Comment by kentcdodds** [comment]
Yeah. Got some stuff in the air right now. But could everyone mention your availability for Wednesday's at that time in January and February?

**Comment by ilyavolodin** [comment]
I currently have no plans scheduled, so any Wednesday should be fine. Unless something changes at the last minute.

**Comment by gyandeeps** [comment]
For me any Wednesday in Jan and Feb works. :) Thanks

**Comment by kentcdodds** [comment]
Hey friends! I've updated the schedule for the upcoming shows. If you could give me your availability for the next 4 available slots in [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md) (excluding the 30th because that wont work for @gyandeeps) that'd be awesome. Thanks!
- 2016-02-10  
- 2016-02-17  
- 2016-02-24
- 2016-03-02

**Comment by feross** [comment]
@kentcdodds Sure! I'm happy to be part of the panel to discuss standard. Any of those time slots works for me.

**Comment by gyandeeps** [comment]
@kentcdodds Any of those dates you mentioned work for me. :+1:

**Comment by ilyavolodin** [comment]
Same here, no plans for any of those dates.

**Comment by kentcdodds** [comment]
Fantastic. Let's plan on the 10th of February at [12:00 CST](http://www.thetimezoneconverter.com/). Really looking forward to this show! I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information as you’d like it to appear on the site and description of the podcast (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name
- An email address to share a Google Doc with you
- Your twitter handle
- A link to your Google+ profile
- Your profile picture at least 180x180px in size

Thanks!

**Comment by gyandeeps** [comment]
@kentcdodds Email sent. Thanks

**Comment by xjamundx** [comment]
I can do Feb. 10 if needed. Happy to help!

**Comment by kentcdodds** [comment]
Sweet! We'd love to have you @xjamundx :-D Please get me your info :point_up_2:

**Comment by kentcdodds** [comment]
Hey everyone! So you should have received an email with a Google Doc for the show. Let me know if you have any questions! Really looking forward to this show!

Also, I recommend you RSVP to [the event on Google+](https://plus.google.com/events/cms6et0sffpkf92nucv1nf70c74) to get it added to your calendar :-)

**Comment by hzoo** [comment]
I'm able to join in if there aren't too many people already

**Comment by kentcdodds** [comment]
Hi @hzoo, I think we're good. Looking forward to the Babel show with you :-)

**Comment by nzakas** [comment]
I'll look forward to watching. :)

Also, I'd happily be a guest when I'm better. I just don't know how far in the future that will be. :(

**Comment by kentcdodds** [comment]
Thanks @nzakas. You get better, then let me know. You'll always have a seat as a guest on the show. You've done enough for the community that we'll always benefit from having you on the show to talk about anything. :+1:

**Comment by hzoo** [comment]
:+1: Will check it out as well!

**Comment by kentcdodds** [comment]
Hey everyone (@feross, @gyandeeps, @ilyavolodin, and @xjamundx)... So I apologize for doing this to you all, but I'm going to be at Forward Web Summit on the date this show is scheduled. I'm hoping to do a live show at the conference. Is there any chance that we can push this back on week to the 17th?

**Comment by feross** [comment]
The 17th is fine for me. Also, sent you an email with my details, as requested before.

**Comment by xjamundx** [comment]
New date is fine.

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information as you’d like it to appear on the site and description of the podcast (if you’d prefer, you can email this info to javascriptair@gmail.com):

Jamund Ferguson
(you know my email)
@xjamundx
https://plus.google.com/u/0/+JamundFerguson
https://cldup.com/glpTjXPw2H-3000x3000.jpeg

**Comment by gyandeeps** [comment]
17th works for me. Thanks

**Comment by ilyavolodin** [comment]
Works for me as well.
