### ISSUE TITLE
Episode Suggestion: Horizon - The realtime JavaScript backend

### ISSUE THREAD

**Issue by tylermcginnis** [javascriptair/site#133]
The RethinkDB team is doing some really interesting stuff with Horizon. I've been chatting with @KittyBot and I think it would make an awesome episode.

Title: Horizon
Idea: Talk all about Horizon
Potential Guests: @KittyBot and anyone else from the Rethink team.

**Comment by kentcdodds** [comment]
Yes please! What do you think @KittyBot?

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by sotojuan** [comment]
@mglukhovsky spoke about Horizon on JS Jabber recently, he'd be a good pick.

**Comment by kentcdodds** [comment]
ping @KittyBot and @mglukhovsky. Would you be interested in talking about Horizon on our show?
