### ISSUE TITLE
Move contact us link to icons

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#134]
Basically this:

<img width="952" alt="screen shot 2016-06-23 at 8 41 40 pm" src="https://cloud.githubusercontent.com/assets/1500684/16325352/ff19555c-3982-11e6-815f-f968b6fdecfa.png">

From [here](https://github.com/javascriptair/site/blob/7f60730b3bcafb2fab232384054c593e57216113/src/pages/home/sections/footer/footer-links-list.js#L31-L35) to [here](https://github.com/javascriptair/site/blob/7f60730b3bcafb2fab232384054c593e57216113/src/pages/home/sections/footer/footer-social-links-list.js#L9-L14).

You'll need to add an svg icon [here](https://github.com/javascriptair/site/blob/7f60730b3bcafb2fab232384054c593e57216113/src/components/icon.js#L7-L21). I'm thinking a normal envelope that looks good with the other icons would be fine.

**Comment by tsriram** [comment]
Let me do this as my first open source contribution :)
