### ISSUE TITLE
Responsiveness and font size in sponsors

### ISSUE THREAD

**Issue by housseindjirdeh** [javascriptair/site#136]
1) Sponsors section needs to fit small screens a bit better 

![sponsors-mobile](https://cloud.githubusercontent.com/assets/12476932/16345376/9ede02d6-3a0f-11e6-9efe-5f5a34639fa3.PNG)

---

2) Font is larger for sponsors in past episodes than in future episodes/homepage for some reason 

Sponsors in past episodes
![sponsors-previousepisodes](https://cloud.githubusercontent.com/assets/12476932/16345537/77845630-3a10-11e6-999b-1cf88d1d7483.PNG)

Sponsors in homepage
![sponsors-homepage](https://cloud.githubusercontent.com/assets/12476932/16345545/80aa2c58-3a10-11e6-8d34-9df1b3f08a1c.PNG)

**Comment by kentcdodds** [comment]
Awesome, yeah, let's fix this.

**Comment by housseindjirdeh** [comment]
If anyone wants to take over this feel free! Otherwise I'll get to it over the weekend :)
