### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#14]
**Title Idea:** Babel, the JavaScript Compiler

**Idea:** Tons of people use this stuff. With Babel 6 out, it'd be super cool to talk about how Babel is a language platform as well as a transpiler. Would be cool to talk about the ecosystem of Babel plugins, respond to the worry that with all of these plugins people will be writing JavaScript that will never run in the browser, etc.

**Potential guest(s):** @sebmck, @thejameskyle, @amasad, @hzoo

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by jamiebuilds** [comment]
Other core members who might be interested: @loganfsmyth, @jmm

**Comment by kentcdodds** [comment]
+1 @thejameskyle. I just nabbed the top 4 contributors according to github :-) Other recommendations of potential guests are totally welcome.

I should mention that I'd especially love to have @sebmck and @thejameskyle on :-)

**Comment by jamiebuilds** [comment]
I'm not interested in doing a live broadcast like this, sorry.

**Comment by amasad** [comment]
Sure. I'm free on Wednesdays at that time.

**Comment by loganfsmyth** [comment]
Hey @kentcdodds, I'd be up for coming on if you'd have me.

**Comment by hzoo** [comment]
Should be able to if we don't have too many people already

**Comment by kentcdodds** [comment]
Cool! Any chance we could get the three of you for the 23rd or 30th at [12:00 CST](http://www.thetimezoneconverter.com/)? (you're still invited @sebmck, and @thejameskyle if you change your mind :))

If that doesn't work, please let me know what Wednesdays work for you in the next 6 weeks.

**Comment by amasad** [comment]
Either Wednesdays should work for me

**Comment by kentcdodds** [comment]
Awesome. @loganfsmyth and @hzoo, do either of those days work for you?

**Comment by hzoo** [comment]
Yeah should be ok - around the holidays!

**Comment by loganfsmyth** [comment]
Either of those should work for me too.

**Comment by kentcdodds** [comment]
Fantastic! Let's plan on December 23rd at [12:00 CST](http://www.thetimezoneconverter.com/) to chat about Babel :-)

Really looking forward to this show! I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information as you’d like it to appear on the site and description of the podcast (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name
- An email address to share a Google Doc with you
- Your twitter handle
- A link to your Google+ profile
- Your profile picture at least 180x180px in size

Thanks!

**Comment by loganfsmyth** [comment]
@kentcdodds 
- Logan Smyth
- loganfsmyth@gmail.com
- @loganfsmyth
- None
- Github avatar is fine: https://avatars2.githubusercontent.com/u/132260?v=3&s=460

**Comment by amasad** [comment]
- Amjad Masad
- amjad.masad@gmail.com
- @amasad
- https://plus.google.com/u/0/+AmjadMasad
- https://avatars0.githubusercontent.com/u/587518?v=3&s=460

**Comment by kentcdodds** [comment]
Alrighty, this show is ready to go. Thanks! You should have received an email with the show Google Doc. Let me know if you have any questions.
