### ISSUE TITLE
Typed JavaScript

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#140]
**Title:** Typed JavaScript with TypeScript and Flow

**Description:** Adding typings to JavaScript is becoming more and more popular. We're going to chat with the creators of TypeScript and Flow to discuss the why and how behind typed JavaScript.

**Potential guest(s):** pending...

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle
- Your profile picture at least 180x180px in size (or you can ask me to just use your github/twitter profile)

Thanks!

**Comment by jeffmo** [comment]
This sounds fun! I'd be down to hop in on this :)

**Comment by kentcdodds** [comment]
Awesome @jeffmo, thanks! @ahejlsberg, would you be interested to come represent TypeScript's perspective on Typed JavaScript for the community?

**Comment by ahejlsberg** [comment]
@kentcdodds Sure, I'm game.

**Comment by kentcdodds** [comment]
Fantastic! I'm really looking forward to this show! I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by kentcdodds** [comment]
Oh, also, which of these dates work for each of you?
- 2016-08-03
- 2016-08-17
- 2016-08-31

Remember, the show is broadcast live at 12:00 CT.

Thanks!

**Comment by jcreamer898** [comment]
![](https://media.giphy.com/media/13XFmJhNtbTSgM/giphy.gif)

**Comment by jeffmo** [comment]
I'm not available on 08-03, but 08-17 and 08-31 both work for me.

**Comment by kentcdodds** [comment]
Ping @ahejlsberg, how's the 17th at 12:00 CT work for you?

**Comment by ahejlsberg** [comment]
@kentcdodds Aug 17th works for me.

**Comment by kentcdodds** [comment]
Actually, how's the 31st of August?

**Comment by ahejlsberg** [comment]
@kentcdodds Aug 31st works!

**Comment by jcreamer898** [comment]
I'm so excited for this one I can't even...
