### ISSUE TITLE
Next Episode Preview Shows Even When On Last Episode 

### ISSUE THREAD

**Issue by kkemple** [javascriptair/site#141]
When watching the last available episode on JavaScript Air the next episode badge is still on top of page and points to the current video.

![javascript_air___web_animations](https://cloud.githubusercontent.com/assets/3629876/16466000/7aa8fbce-3e0f-11e6-9f00-eba2e53164be.png)

**Comment by kentcdodds** [comment]
This is a great point! I don't want to remove it for all pages, but definitely makes sense to not include it if the `nextEpisode.id === episode.id`. Should be fairly trivial to fix. Relevant code is around [here](https://github.com/javascriptair/site/blob/489bc994d7bc36a4707cef441990ac9ab6dd847f/src/components/header.js#L135-L138) and [here](https://github.com/javascriptair/site/blob/489bc994d7bc36a4707cef441990ac9ab6dd847f/src/pages/episode/index.js#L29). I'm thinking that you can pass a new prop to the `header.js` component that indicates whether to show the `EpisodeBox`.

Anyone wanna try this? See the [contributing guidelines](https://github.com/javascriptair/site/blob/489bc994d7bc36a4707cef441990ac9ab6dd847f/CONTRIBUTING.md)

**Comment by kkemple** [comment]
I could do it, no sense in not doing it 😄

**Comment by kentcdodds** [comment]
Sweet! Don't forget [this important step](https://github.com/javascriptair/site/blob/489bc994d7bc36a4707cef441990ac9ab6dd847f/CONTRIBUTING.md#add-yourself-to-the-contributors-page) :-)

**Comment by kkemple** [comment]
ahaha i won't 😉
