### ISSUE TITLE
Promises in Javascript

### ISSUE THREAD

**Issue by anirudh-modi** [javascriptair/site#144]
Hello Kent,

Promises in Javascript has evolved quite a bit, from earlier using Library for promise to shifting in native, I feel, if the viewers can some insight on promises, it can be really helpful, especially for a beginner coming new to JS.

**Comment by kentcdodds** [comment]
Hi @anirudh-modi!
This sounds like a great show! I saw your recommendation on [jsair.io/suggestions](http://jsair.io/suggestions). In the future, that will be sufficient. Thanks!

**Comment by anirudh-modi** [comment]
Great!

**Comment by Connorelsea** [comment]
That suggestions link "http://jsair.io/suggestions" does not work for me. Says "Page not Found" on a shortlink website. Just letting you know! @kentcdodds

**Comment by kentcdodds** [comment]
Sorry, that's http://jsair.io/suggest
