### ISSUE TITLE
Managing Dependencies like a boss 😎

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#145]
**Title:** Managing Dependencies like a boss 😎

**Description:** The average npm project has [100](http://blog.npmjs.org/post/146943134240/npm-add-ons) dependencies and subdependencies. Managing these dependencies can be challenging. We're going to talk with the great people behind [DependencyCI](https://dependencyci.com/), [Libraries.io](https://libraries.io/), and [Greenkeeper.io](https://greenkeeper.io/) about how to make managing these dependencies easier.

**Potential guest(s):** @andrew and @boennemann (any other people you'd recommend who'd have a unique perspective on this? Please suggest them!)

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by andrew** [comment]
Thanks for the invite, I can do 2016-08-17, 2016-08-31 or 2016-09-07.

name: Andrew Nesbitt
email: andrewnez@gmail.com
twitter: @teabass

Thanks!

**Comment by kentcdodds** [comment]
Great! How about you @boennemann?

**Comment by boennemann** [comment]
Yay, thanks again for the invite @kentcdodds. I'm happy to join on all dates @andrew mentioned, but would prefer the earliest date 2016-08-17.
- Stephan Bönnemann
- stephan.boennemann at gmail.com
- @boennemann

It would be cool to have someone from npm on the show. @ashleygwilliams or @bcoe maybe? :)

**Comment by kentcdodds** [comment]
Oh! I'd love to have both @ashleygwilliams and @bcoe on! Ashley joined us [before](http://jsair.io/learning) and we had a splendid time. I've really admired Benjamin's work on `nyc` so I'd love to have him on as well! What do ya'll think?

**Comment by bcoe** [comment]
@kentcdodds I'd be happy to chat on this topic, my schedule is pretty flexible -- [npm Camp](http://npm.camp/)  being my only upcoming obligation on the 30th of July.
- **Name:** Ben Coe
- **Email:** ben [at] npmjs.com
- **Twitter:** @BenjaminCoe

**Comment by kentcdodds** [comment]
Great! Would love to have you too @ashleygwilliams

**Comment by ashleygwilliams** [comment]
sure thing! 
- Name: Ashley Williams
- Email: ashley [at] npmjs.com
- Twitter: @ag_dubs

**Comment by kentcdodds** [comment]
Sweet! We're on the schedule for the 17th of August. Really looking forward to this show 😺

**Comment by kentcdodds** [comment]
Alrighty! The show is on the website now (with your avatars and names, please double check that it looks ok). You should have received an email inviting you to a Google Doc. If you didn't, let me know.

As always, let me know if you have any questions 😄  Looking forward to the show!
