### ISSUE TITLE
Live @ ConnectJS

### ISSUE THREAD

**Issue by timdorr** [javascriptair/site#146]
In a similar vein to #46, since you'll be there (and I'll be there! yay!), why not do a show live from ConnectJS as well? 

http://connect.tech/

**Comment by kentcdodds** [comment]
Thanks for the suggestion @timdorr. We'll see if I can make it work. Not 100% certain that JSAir will still be running by then. Even if it is, on site shows take a bit of extra work and I'm already doing a workshop and a talk. I think throwing an on-site show on top of that could do me in.
