### ISSUE TITLE
YouTube Live Calendar

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#147]
So with Hangouts on Air moving from Google+ to YouTube live you can no longer get the event added to your calendar by RSVP-ing to the event. This is unfortunate. So I've setup [this calendar](https://calendar.google.com/calendar/embed?src=9617vll2ovv6p9f6k1loargbbs%40group.calendar.google.com&ctz=America/Denver) with the JavaScript Air google account so people can subscribe to it and get notifications when the events are about to start.

That's great, except it's yet _another_ manual step to add the event to the calendar. So I'm looking for someone to either keep it updated or automate the calendar for me. Anyone up for the challenge?

**Comment by aarondolson** [comment]
I'd be happy to help out, let me know.

**Comment by kentcdodds** [comment]
Sweet! Could you send me an email and I'll give you access to the calendar. Thank you!

**Comment by kentcdodds** [comment]
Thanks a ton for the help @aarondolson!
