### ISSUE TITLE
Node.js and Community

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#148]
**Title:** Node.js and Community

**Description:** ... coming soon

**Potential guest(s):** @hackygolucky, @mikeal, and @emilyrose

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

I received an email from Zibby Keaton indicating that ya'll would like to join us for an episode about Node.js and Community. Let's plan on the 7th of Sept. Does that work?

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by ZibbyKeaton** [comment]
@kentcdodds: @mikeal will not be able to make this. But, @TheAlphaNerd (Myles Borins) and @jasnell (James Snell) are down to join.

**Comment by kentcdodds** [comment]
Thanks @ZibbyKeaton. @emilyrose, can you make it too?

**Comment by kentcdodds** [comment]
Would ya'll be alright if I try to invite people from some other communities here so we can get a few more perspectives? I'm thinking of some people from the Hoodie project who have done a stellar job with their community.

cc @mikeal, @TheAlphaNerd, @jasnell, @emilyrose

**Comment by kentcdodds** [comment]
FYI, @TheAlphaNerd, @jasnell, you're on the schedule (and [site](https://javascriptair.com/episodes/2016-09-07/)) for next week! Looking forward to it!

**Comment by jasnell** [comment]
@kentcdodds ...

> Would ya'll be alright if I try to invite people from some other communities here so we can get a few more perspectives?

Absolutely! Looking forward to it.

**Comment by ZibbyKeaton** [comment]
Also, I know @hackygolucky was interested in participating too. She's currently on vacation, but will likely confirm when she's back next week.

**Comment by kentcdodds** [comment]
Sweet! I'd like to officially invite @hackygolucky and @gr2m to join us!

**Comment by gr2m** [comment]
I'd be honored, big fan of the show :) I can make it next Wednesday

**Comment by hackygolucky** [comment]
@kentcdodds Howdy! Just saw the ad for the show and have been super backed up in email from vacation time today. Do you still need more chatters? I thought @emilyrose had mentioned interest via email, too. If that's enough folks, I'm fine to sit this one out.

**Comment by kentcdodds** [comment]
Definitely! The more the merrier IMO. Happy to have both of you on the show!

**Comment by affinity-matrix** [comment]
Oh hey. I just saw the link to this thread. I'm still happy to be a part if it's deemed helpful. Thanks!

**Comment by kentcdodds** [comment]
Wonderful! I'll add you both on the site. I love having many perspectives on the show. Could I get y'all's email, name, and twitter? That's all I need.

**Comment by hackygolucky** [comment]
@kentcdodds awesome. 

Tracy Hinds
tracyhinds at linuxfoundation dot org 
@hackygolucky

**Comment by affinity-matrix** [comment]
@kentcdodds sure!

Emily Rose
erose AT-SYMBOL salesforce PERIOD com
@nexxylove on Twitter

**Comment by kentcdodds** [comment]
Awesome! We're all set to go. Let me know if you have any questions before the show! I sent ya'll a Google Doc (let me know if you didn't get it). Here's the Pre Show notes:
- Please jump on 15 minutes before the show to do a tech/mic/camera check
- Make sure you’re familiar with the [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT)
- Be sure to add tips and picks to the document below
- If you have any questions about the show check out [the Guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing)
- Shortcut to toggle mute is ⌘+D (ctrl+D)

**Comment by ZibbyKeaton** [comment]
@kentcdodds: Due to a family emergency, Emily is not longer able to make it. Also, if you could send the Google+ hangout invite to James at jasnell@gmail.com that would be preferred as he won't get it otherwise.

**Comment by kentcdodds** [comment]
Thanks everyone! It was a great show. Sorry we missed you @emilyrose. We'll have to have you on another time!
