### ISSUE TITLE
Testing Tooling

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#149]
**Title:** Testing Tooling

**Description:** ... coming soon...

**Potential guest(s):** @TheAlphaNerd (suggestions?)

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by sotojuan** [comment]
Since there's no description I'm just going to throw a wild guess and say I can represent AVA and talk about the tools and modules we use for testing (in AVA and out of AVA itself)—if the show isn't about that stuff then it's fine 😄

**Comment by kentcdodds** [comment]
Yes! You're welcome to join! In fact I had you in mind!

**Comment by sotojuan** [comment]
Yay! I have an appointment at 10am on the 14th and I don't know when it will end, so to be safe I'd rather go any date after that.

**Comment by sotojuan** [comment]
Someone else: @twada (power assert).

**Comment by kentcdodds** [comment]
Thanks @sotojuan, but I think that power-assert is a little more specific a tool than I'm thinking about for this show.
