### ISSUE TITLE
e2e testing

### ISSUE THREAD

**Issue by yuyokk** [javascriptair/site#15]
**Title Idea**: e2e testing

**Idea**: Is it worth doing at all? What are benefits? How much time should it take? e2e testing with some frameworks like React and Angular.

**Potential guest(s)**: not sure here

Please let me know if this makes sense.

**Comment by kentcdodds** [comment]
Totally makes sense. Good suggestion. I'll give it some thought and feel around the JS community for E2E experts.

**Comment by yuyokk** [comment]
@kentcdodds :+1: cool
I'm excited about the upcoming podcasts! Thanks for doing this :clap:

**Comment by pselle** [comment]
I would love to have @juliemr on the show!

**Comment by kentcdodds** [comment]
@juliemr was on the Angular Air version of this show. :D

I think that you'd be great to have on JavaScript Air! JavaScript Air is pretty much what you think it is. Shows are on Wednesdays at 12:00 CST. What do you think?

**Comment by juliemr** [comment]
@kentcdodds sure, I'd be interested!

**Comment by kentcdodds** [comment]
Awesome! Let's schedule a good day then! Could you let me know if any of the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md) work for you at [12:00 CST](http://www.thetimezoneconverter.com/)?

**Comment by juliemr** [comment]
16/3/2, 16/3/16 16/3/30 all would work.

**Comment by kentcdodds** [comment]
Fantastic! Let's go with the 2nd of March then! I'm pretty sure I've got all of your information. I'll let you know when the website's updated and you should receive an invite to a Google Doc eventually :-)

**Comment by kentcdodds** [comment]
Also, thanks, I think this is going to be great! :D

**Comment by kentcdodds** [comment]
Oh no! @juliemr, I dropped the ball on this one and forgot to add your show to the schedule :-( Will the 16th of March still work for you?

**Comment by juliemr** [comment]
@kentcdodds Yeah, 16th March would work just as well!

**Comment by kentcdodds** [comment]
Great! I'll get everything set up. I'm sorry about that :-/ Looking forward to the show!

**Comment by kentcdodds** [comment]
Also, please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Don't bother sending me anything. I already have everything I need from you to get this scheduled. Thanks!

**Comment by kentcdodds** [comment]
Hi @juliemr! You should have received a Google Doc from me. Let me know if you haven't. Looking forward to the show next week!
