### ISSUE TITLE
Web Components

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#150]
**Title:** Web Components

**Description:** ...pending

**Potential guest(s):** @slightlyoff, @notwaldorf, @robdodson, @jakearchibald

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

[ref](https://twitter.com/kentcdodds/status/771512498826596353)

**Comment by kentcdodds** [comment]
One of the things that I try really hard to do for the show is invite people with different backgrounds and perspectives on the same topic to come together to have a positive discussion. So I'm going to invite @tusharmath creator of [rwc](https://github.com/tusharmath/rwc) to join us!

**Comment by robdodson** [comment]
Rob Dodson
robdodson@google.com
@rob_dodson

**Comment by kentcdodds** [comment]
Sweet, thanks Rob. What days from [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md) work for you?

**Comment by robdodson** [comment]
9/28 and 10/12 work

**Comment by tusharmath** [comment]
@kentcdodds Thanks for the invitation 

Tushar Mathur
tusharmath@gmail.com
@tusharmath

Available on @robdodson mentioned dates.

**Comment by notwaldorf** [comment]
9/28 and 10/12 work for me too!

**Comment by kentcdodds** [comment]
Alrighty! I'm going to schedule us for 9/28 (next week). You'll get an invite to a Google Doc and a calendar event :) Thanks!

**Comment by kentcdodds** [comment]
@notwaldorf, could you email me (I can't find your email address): javascriptair@gmail.com

Thanks!

**Comment by notwaldorf** [comment]
@kentcdodds done!

**Comment by jakearchibald** [comment]
I probably shouldn't be part of this. My web components knowledge is towards zero.

**Comment by kentcdodds** [comment]
Haha, that's fine @jakearchibald! I'll get you on the show eventually...

![what-exactly-would-you-say-you-do-here](https://cloud.githubusercontent.com/assets/1500684/18748845/730cec76-8091-11e6-9ec2-05cfed9616d3.jpg)
