### ISSUE TITLE
Test all the things with Cypress

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#153]
**Title:** Test all the things with Cypress

**Description:** Cypress.io is an automated testing tool that runs in the context of the browser and has some really solid features that make unit, integration, and even end to end testing much easier!

**Potential guest(s):** @brian-mann, @RandallKent

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by kentcdodds** [comment]
Note: I'm hoping that we can do it this Wednesday. If that doesn't work, let me know a few days on the schedule that work for you.

**Comment by RandallKent** [comment]
This Wednesday, September 21st, is perfect!

From Cypress, @brian-mann will be joining (I'll just be listening). In addition, @bahmutov will also be joining us as a user of Cypress. 

An email will be hitting javascriptair@gmail.com shortly with contact info for the Google Doc!

**Comment by kentcdodds** [comment]
Alrighty, I think we're all set! The website will be updated as soon as travis starts and finishes [this build](https://travis-ci.org/javascriptair/site/builds/161349199)
