### ISSUE TITLE
Async Patterns

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#158]
**Title:** Async Patterns in JavaScript

**Description:** One of the distinctive aspects of JavaScript is how it deals with asynchronous operations (like reading a file or making a request to a database or server). We're going to talk about the different patterns you can follow with async in JavaScript

**Guest(s):** @focusaurus

We're going to do this show tomorrow. More info coming to your inbox. Looking forward to it!

**Comment by kentcdodds** [comment]
Inviting @vkarpov15 of the [co](http://npm.im/co) community to join :+1:

**Comment by vkarpov15** [comment]
- Name: Valeri Karpov
- Twitter: @code_barbarian
- Email: val@karpov.io

Also, just to confirm, the time is 12:00 pm (noon) in America/Los_Angeles?

**Comment by focusaurus** [comment]
- Name: Peter Lyons
- Twitter/Github: @focusaurus
- Email: pete@peterlyons.com
- Web: http://peterlyons.com

**Comment by focusaurus** [comment]
@kentcdodds can you please put the URL to the hangout in the google doc when you are ready?

**Comment by kentcdodds** [comment]
Done! Thanks! :)

**Comment by vkarpov15** [comment]
Hi Kent and co, I just wanted to say thanks again for having me on. Had a great time and learned a bunch :+1:

**Comment by kentcdodds** [comment]
Thanks again for coming on! It was great!
