### ISSUE TITLE
Yarn (bonus show)

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#159]
**Title:** The Yarn package client

**Description:** [Yarn](https://yarnpkg.com/) bills itself as fast, reliable, and secure dependency management. It was [recently released](https://code.facebook.com/posts/1840075619545360) as a collaborative effort with developers from Facebook, Google, and Tilde. In this bonus show, we're going to talk about what this means for the JavaScript community.

**Potential guest(s):** @kittens, @thejameskyle, @cpojer, @wycats, @bestander

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

**NOTE**: JavaScript Air is going to be officially ending on November 2nd and all the shows between now and then are already planned. But James asked me to do this show and I want to anyway. So we'll do this as a "bonus" show. Normally the show is on Wednesday at 12:00 CT. For this one, we'll need to come up with a different time. Here are some suggestions:
1. 2016-10-17 at 12:00 PM CT (anytime after 11:00 AM CT works for me)
2. 2016-10-18 at 2:00 PM CT (anytime after 1:00 PM CT works for me)
3. 2016-10-24 at 12:00 PM CT (anytime after 11:00 AM CT works for me)
4. 2016-10-25 at 12:00 PM CT (anytime after 11:00 AM CT works for me)

Let me know whether you're interested and which of the times work for you. Thanks!

**Comment by cpojer** [comment]
We discussed doing this on November 2nd ~10am CT with @kittens, @bestander and likely @wycats :)

**Comment by kentcdodds** [comment]
You should have received an email with an invite to a Google Doc (@kittens, you didn't because I couldn't find your email address, could you send it to me? [mailto:javascriptair@gmail.com](javascriptair@gmail.com)). I'm looking forward to the show! Thanks!

If you would, please add the event to your calendar! Use [this link](http://www.google.com/calendar/event?action=TEMPLATE&ctz=America%2FChicago&dates=20161102T100000%2F20161102T110000&details=Episode%20047%20of%20the%20live%20JavaScript%20broadcast%20podcast.%20Yarn%20bills%20itself%20as%20fast%2C%20reliable%2C%20and%20secure%20dependency%20management.%20It%20was%20recently%20released%20as%20a%20collaborative%20effort%20with%20developers%20from%20Facebook%2C%20Google%2C%20and%20Tilde.%20In%20this%20bonus%20show%2C%20we%27re%20going%20to%20talk%20about%20what%20this%20means%20for%20the%20JavaScript%20community.&location=http%3A%2F%2Fjsair.io%2Fyarn&sprop=http%3A%2F%2Fjsair.io%2Fyarn&sprop=name%3AJavaScript%20Air&text=JavaScript%20Air%20Episode%20047%3A%20Yarn%20%28bonus%20show%29%20with%20Sebastian%20McKenzie%2C%20Konstantin%20Raev%2C%20Yehuda%20Katz%2C%20and%20Christoph%20Pojer&trp=false) if you're using Google Calendar.
