### ISSUE TITLE
Web Performance

### ISSUE THREAD

**Issue by toddhgardner** [javascriptair/site#16]
**Title Idea:** Web Performance

**Idea:** The nitty-gritty details of understanding web performance.

**Potential guest(s):** Nik Molnar, @nikmd32

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by kentcdodds** [comment]
@toddhgardner, looks like @nikmd32 should be: @nikmd23 :-) What do you think Nik?

**Comment by toddhgardner** [comment]
Doh!

**Comment by nikmd23** [comment]
I'd love to do a show! Thanks for thinking of me.

When are shows usually recorded? Evenings? Afternoons?

**Comment by kentcdodds** [comment]
Hi @nikmd23! That's great!

> Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

Because it's Live there is a minimal amount of flexability with the time. If we must though, we can move it around.

Which Wednesdays work well for you in the next 4-6 weeks? We do need to fill a slot on the 23rd and the 30th. Would either of those work for you?

**Comment by nikmd23** [comment]
So basically: "Look up there  :point_up: you dum dum".  :flushed:

Sorry for missing that. 

I can make December 16th, or January 13, 20 or 27 work.

**Comment by kentcdodds** [comment]
Hee hee, didn't want to say it like that :P

Let's plan you for the 16th :-) Do you know anyone else who could contribute to this conversation? Feel free to @ mention them here and we'll see if we can sync schedules.

**Comment by nikmd23** [comment]
@kentcdodds I'm so sorry. The business trip I'm currently on has been extended, and I'm no longer available on the 16th. :disappointed: 

Can we try for on of the 2016 dates?

**Comment by kentcdodds** [comment]
Haha! How fortunate! I'm not sure what I was thinking, but we actually already have a show scheduled for the 16th. Let's plan on January 13th :-)

**Comment by kentcdodds** [comment]
Really looking forward to this show! I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information as you’d like it to appear on the site and description of the podcast (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name
- An email address to share a Google Doc with you
- Your twitter handle
- A link to your Google+ profile
- Your profile picture at least 180x180px in size

Thanks!

**Comment by kentcdodds** [comment]
Alrighty, I've almost all the info I need from the interwebs. This episode is up on the website. I just need your email address to share a google doc with you :-) Feel free to email it to me if you don't want it public: javascriptair@gmail.com

**Comment by nikmd23** [comment]
Awesome! My email is nikmd23@gmail.com

**Comment by kentcdodds** [comment]
@nikmd23, just noticed that you were just on JavaScript Jabber for this exact same topic. I don't mind doing repeats, but I prefer not to do the exact same guest on the exact same topic so close to when a subject has been covered by another podcast.

This is not a reflection on you. We're doing this for the community and there's a lot of other content to cover so I think I'm probably going to take a raincheck on this episode and maybe we'll come back to it in a few months.

**Comment by nikmd23** [comment]
No problem @kentcdodds - I understand.

**Comment by kentcdodds** [comment]
@nikmd23, I just listened to that episode on JSJabber. Super good stuff (just like your first episode on there). Thanks!
