### ISSUE TITLE
"Add to calendar"/tweet URL for upcoming Ep 46 goes to Ep 43

### ISSUE THREAD

**Issue by aarondolson** [javascriptair/site#163]
https://javascriptair.com/episodes/2016-10-26/
When you click "Add to Calendar" or tweet it out the URL is listed as http://jsair.io/2016-10-05 which goes to Episode 43

**Comment by kentcdodds** [comment]
Ah! Thanks for pointing that out! Would you like to fix that episode's short URL to be: http://jsair.io/react-native
And I'll set that URL soon.

**Comment by aarondolson** [comment]
No problem, should be fixed - submitted the pull request w/changes
