### ISSUE TITLE
Black panelist names

### ISSUE THREAD

**Issue by vblazenka** [javascriptair/site#168]
Hi, I saw on twitter that you are looking for a help with fixing this.

I would be glad to help if you approve my help.

Cheers!

**Comment by kentcdodds** [comment]
Wonderful! Please do! Make sure to follow the [contributing guidelines](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md) (especially the bit [here](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#add-yourself-to-the-contributors-page)).

The relevant code is around [here](https://github.com/javascriptair/site/blob/master/src/pages/home/sections/panelists.js). Thanks!

**Comment by vblazenka** [comment]
Thanks, I'm on it! :)

**Comment by kentcdodds** [comment]
This file will also be useful: https://github.com/javascriptair/site/blob/master/src/components/person.js

**Comment by vblazenka** [comment]
@kentcdodds Sorry for taking this long I had some trouble with Node version.

I tracked this to person.js:

```

const text = {
  transition: 'all 0.4s',
  color: '#f8f8f8', // it was black
  padding: '5px 10px',
  fontSize: '1em',
  ':visited': {color: '#adadad'},
}
```

I changed color and I tested the site and all colors were right as I could tell.
If you think this is okay, and if you approve f8f8f8 for color, it should be it. :)

EDIT: Or maybe I can remove default color from the text so that we avoid later overriding troubles?
EDIT2: I tried removing default colors, but then I have to go to every page that is using Person and create a style with color for name and twitter.

**Comment by kentcdodds** [comment]
Yeah, we should probably pass along a prop that allows you to configure the text color and have it default to black or something. Could you do that?

**Comment by vblazenka** [comment]
Can you give me an example of that prop? 

Are you sure that this problem is worth of prop?

btw. I think that easiest solution, for now, is to include aphrodite with no-important (I'm not sure what you think of that)  and put important only for text centering. 
Panelist.js has personName and personTwitter styles and for example contributors text color will default to black. 

What do you think about  this approach with no-important?

**Comment by kentcdodds** [comment]
You'd have to create it yourself. Actually, what would probably be best is to move [these styles](https://github.com/javascriptair/site/blob/master/src/components/person.js#L60-L67) into the render function [here](https://github.com/javascriptair/site/blob/master/src/components/person.js#L16) (in it's own `StyleSheet.create` call), and then mixin (with object spread) a prop that you would create called `customStyles` or something and pass that in [here](https://github.com/javascriptair/site/blob/master/src/pages/home/sections/panelists.js#L59-L64).

Does that make sense?

**Comment by vblazenka** [comment]
Hey, I'm sorry I'm new to Aphrodite and it's taking me much longer and I don't have time tonight anymore, maybe I can jump on creating that props this weekend or you can open issue and find someone else.

But I can provide some easy fix, for now, to make the site look okay. My proposal is to import aphrodite/no-important. 

Here is the whole diff in screen shot below.

<img width="483" alt="screen shot 2016-11-03 at 22 28 09" src="https://cloud.githubusercontent.com/assets/1723170/19985866/e9360b04-a214-11e6-86ec-253a39e04668.png">

**Comment by kentcdodds** [comment]
Hey @wedranb, thanks so much for spending time on this. I really appreciate it. Sorry it wasn't an easier fix. I think I'll just go ahead and do this one. Hopefully you at least learned something new from this! :)

**Comment by vblazenka** [comment]
Oh yes I did, thanks!

**Comment by elderfo** [comment]
hey @kentcdodds, I blindly looked into this issue before seeing the logged issue. In reading your comments, I was curious if you would want to pass a plain js object to the `customStyles` prop or if you would use aphrodite to convert it into another form?

**Comment by kentcdodds** [comment]
I looked at it last night and found that there are a few fundamental things that I'm not doing quite right. I need to rework some things. If you want to give it a try, feel free, but I think ultimately I need to refactor everything to not pass around class names, but to pass around style objects and merge them together before passing them to `StyleSheet.create`. It'll take a bit of rework...

**Comment by elderfo** [comment]
Granted I am not super familiar with the whole application, it looks like a minor change could accomplish a fix for this and introduce to the `customStyles` concept in an incremental fashion, preventing a large scale refactor. 

Would you mind if i threw up a pull request and we can talk about it?

**Comment by kentcdodds** [comment]
Sure :) knock yourself out :)
