### ISSUE TITLE
JavaScript Debugging

### ISSUE THREAD

**Issue by toddhgardner** [javascriptair/site#17]
**Title Idea:** JavaScript Debugging

**Idea:** Tools and techniques for debugging JavaScript applications. Understanding stacktraces, async stacktracing, sourcemaps, realtime tracing, etc.

Could be 2 shows, one for browser, one for node.

**Potential guest(s):** @toddhgardner, @jaymundx

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by kentcdodds** [comment]
@toddhgardner, did you mean @xjamundx? Or is @jaymundx supposed to reference someone else?

**Comment by toddhgardner** [comment]
No, you're correct. Damn, i gotta double check these things first :p.
I saw him do a talk at MtnWestJS a few years ago about what PayPal was doing and it was cool. Not sure if he's still in the space though.

**Comment by xjamundx** [comment]
Right @toddhgardner we both had error handling talks back to back. You know....@stinkydofu from netflix has been talking a lot about error handling in node lately (here's a recent http://www.slideshare.net/AlexLiu24/to-err-is-human-54101650) also his colleague has a talk about debugging here http://yunong.io/2015/11/13/debugging-node-js-in-production/. They might be good folks. I've been focusing more heavily client-side lately so I may be a bit rusty in the node debugging area!

**Comment by kentcdodds** [comment]
@xjamundx, thanks for the referral. Though I don't think that @stinkydofu is a user on GitHub. Typo?

**Comment by xjamundx** [comment]
Try @DonutEspresso

**Comment by kentcdodds** [comment]
What do you think @DonutEspresso?

**Comment by DonutEspresso** [comment]
Hey folks - @yunong and I have definitely been spending more time on the Node.js side of things. Yunong's experience with debugging in Node is ace, and you'll definitely want him on board for the Node stuff. I'd be happy to join too, depends on how many guests you want. :)  I think Yunong's traveling for the next week or two though.

**Comment by kentcdodds** [comment]
I'm fine with a bunch of guests (probably up to 4 or so). @toddhgardner, @DonutEspresso, and @yunong (if you're interested which I hope you are!), please tell me your availability for these dates:
- 30 December 2015
- 20 January 2015
- 27 January 2015
- 3 February 2015
- 10 February 2015

**Comment by kentcdodds** [comment]
Oh, and remember the show is 1 hour and starts at [12:00 CST](http://www.thetimezoneconverter.com/)

**Comment by toddhgardner** [comment]
Awesome, a panel on the topic sounds great.
I can do it:
- 30 December 2015
- 27 January 2015
- 10 February 2015

**Comment by DonutEspresso** [comment]
The Jan/Feb dates work for me.

**Comment by kentcdodds** [comment]
Great @yunong, are you interested? Would love to have you

**Comment by DonutEspresso** [comment]
He's OOO on vacation, so I imagine he has limited access to internet. I don't think he'll be back in town until last week of Dec.

**Comment by kentcdodds** [comment]
Alright, why don't we schedule something and just hope he can make it. Why don't we plan on the 3rd of February?

**Comment by kentcdodds** [comment]
Alrighty, we're all set! You should both have received an email from me with a Google Doc.  Be sure to RSVP to [this event](https://plus.google.com/events/c36b25girvo89474lqo92loikic) to get it added to your calendar. @yunong you're still invited. Let me know if you're interested.

Let me know if you have any questions. Looking forward to the show!

**Comment by yunong** [comment]
I'm in, looking forward to it.

**Comment by kentcdodds** [comment]
Fantastic @yunong! Really looking forward to this show! I need a few things from @yunong to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information as you’d like it to appear on the site and description of the podcast (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name
- An email address to share a Google Doc with you
- Your twitter handle
- A link to your Google+ profile
- Your profile picture at least 180x180px in size

Thanks!
