### ISSUE TITLE
Not working on Windows vista 32-bit. following error show all time 

### ISSUE THREAD

**Issue by JiteshTripathi** [javascriptair/site#174]
The syntax of the command is incorrect.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! reactjs-basics@1.0.0 build: `webpack -d && copy src/index.html dist/ind
ex.html && webpack-dev-server --content-base src/ --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactjs-basics@1.0.0 build script 'webpack -d && copy src
/index.html dist/index.html && webpack-dev-server --content-base src/ --inline -
-hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactjs-basics packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -d && copy src/index.html dist/index.html && webpack-dev-se
rver --content-base src/ --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactjs-basics
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactjs-basics
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     H:\rectjsPratice\reactjs-basics-master\reactjs-basics-master\npm-de
bug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! reactjs-basics@1.0.0 start: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactjs-basics@1.0.0 start script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactjs-basics packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactjs-basics
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactjs-basics
npm ERR! There is likely additional logging output above.

**Comment by kentcdodds** [comment]
I think that you've logged this to the wrong repository...
