### ISSUE TITLE
Selecting JavaScript Frameworks & Libraries

### ISSUE THREAD

**Issue by nikmd23** [javascriptair/site#18]
**Title Idea:** Selecting JavaScript Frameworks & Libraries

**Idea:** The process of finding the right JavaScript "needles" for your project in the "haystacks" of NPM, Bower & GitHub. 

**Potential guest(s):** Anthony van der Hoorn @avanderhoorn

If you haven't heard of [JavaScript Air](http://javascriptair.com/) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by avanderhoorn** [comment]
I'm happy to chat. Just let me know what I need to do.

**Comment by kentcdodds** [comment]
I'm actually thinking I'd combine this episode with #19. I'll keep you informed :-)

**Comment by avanderhoorn** [comment]
No worries, just let me know.
