### ISSUE TITLE
REST to GraphQL Transition

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#21]
**Title Idea:** Transitioning from REST to GraphQL

**Idea:** We've heard about [GraphQL](https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html) [quite](https://www.youtube.com/watch?v=cr4QB3j8qFc) [a](https://www.youtube.com/watch?v=gY48GW87Feo) [bit](https://www.youtube.com/watch?v=S0s935RKKB4). We know that there are problems with REST and GraphQL solves many of those problems. But now we have a new problem: Transitioning from REST to GraphQL. Let's talk about what it takes to do that well and how services need to adapt to this new way of thinking about data access.

**Potential guest(s):** @leebyron, @schrockn

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few [available slots](https://github.com/javascriptair/site/blob/master/other/schedule.md). Thanks!

This idea was originally mentioned in #20 by @Norm-, I like the idea a lot and think it deserves its own episode. Feel free to suggest anyone else you think might be able to contribute to this conversation!

**Comment by leebyron** [comment]
I'm happy to participate

**Comment by kentcdodds** [comment]
Awesome! How about you @schrockn? Loved [your React Rally talk](https://www.youtube.com/watch?v=KOudxKJXsjc), I think it'd be great to have you on the show on this topic specifically. That talk addressed subject a bit. What do you think?

Also, for both of you, what's your availability like for the available slots in [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md)?

**Comment by schrockn-zz** [comment]
I'm definitely interested. I'd be available for most dates starting in April.

**Comment by kentcdodds** [comment]
How about April 6th?

**Comment by kentcdodds** [comment]
@leebyron and @schrockn, here's [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md). Which of these dates work well for you?
- 2016-03-30
- 2016-04-14
- 2016-04-20

**Comment by leebyron** [comment]
4/14 works for me, the other two days conflict with travel.

**Comment by kentcdodds** [comment]
Sounds great. Will that work alright for you too @schrockn?

**Comment by schrockn-zz** [comment]
4/14 should work for me sounds great!

**Comment by kentcdodds** [comment]
Oh, whoops. Not sure how that happened. That should be 4/13 actually. Does that still work for both of you?

**Comment by leebyron** [comment]
Yep, still good

**Comment by kentcdodds** [comment]
Ping @schrockn, I'm going to assume (read: hope) that you can make it on the 13th (sorry about the mixup). I'll put it on the site that way. If that doesn't work, please let me know and we can work something out :-) Really looking forward to this show!

**Comment by kentcdodds** [comment]
Oh, and one other question. Do you know of anyone in the community who has actually made the transition from REST to GraphQL? Would be great to have them on as well :+1:

**Comment by leebyron** [comment]
Hey @kentcdodds - bad news, I spoke too soon with the 13th. That's actually the [f8](https://www.fbf8.com/) conference which I'm a presenter for.

I see 5-18 is the next open slot in your schedule. I'm free then if that's a reasonable new time.

**Comment by kentcdodds** [comment]
Hey Lee! Bummer! We can definitely reschedule. Could you bug @schrockn to let me know if 5-18 works for him? Thanks!

**Comment by kentcdodds** [comment]
Hey @leebyron and @schrockn! Looking forward to tomorrow's show! You should have received an email inviting you to [the show notes Google Doc](https://docs.google.com/document/d/1A-RLPJD7eGgfIU3LkVAKkeeHv2WPUCYnvqgsUB8Srzo/edit). Please take a quick look at it and let me know if you have any questions!
