### ISSUE TITLE
Firefox DevTools, React, and Redux

### ISSUE THREAD

**Issue by linclark** [javascriptair/site#22]
@kentcdodds suggested we do an episode on Firefox DevTools.

**Title**: TBD

**Date**: January 13

**Tentative description** (feel free to suggest something else): 
React is in your browser. Not just in web pages, but in the browser itself. We talk with developers from Firefox's Developer Tools team about how they're using React and Redux to build developer tools, and how the two make the DX (developer experience) of building developer tools better.

Potential guests: @jlongster and @jsantell are in.

I'm thinking we could talk about devtools and how they work for a bit, and then talk about how the Firefox DevTools team is breaking up its frontend into components.

**Comment by kentcdodds** [comment]
Really looking forward to this show! I need a few things from you all (except you @linclark) to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle
- Your profile picture at least 180x180px in size (can just be your twitter/github profile)

Thanks!

**Comment by kentcdodds** [comment]
Ping @jlongster and @jsantell, could you both get me the info requested above so I can get this episode on the website? Thanks!

**Comment by jlongster** [comment]
Sorry, missed the previous mention!
- James Long
- longster@gmail.com
- jlongster
- profile: https://pbs.twimg.com/profile_images/622146266823155712/RjmeRIOn.jpg

**Comment by vramana** [comment]
I would like to see both Chrome and Firefox DevTools people on the same show. It would be interesting to know both their view points. May you can invite @paulirish or @paullewis from the chrome team ??

**Comment by kentcdodds** [comment]
I think there's enough content for each to have their own show. Since you bring it up...

 @paulirish or @paullewis, would either of you be interested to come on the show sometime? 

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next few weeks. Thanks!

**Comment by kentcdodds** [comment]
Alrighty, the website's updated. @jsantell, could you get me your email address so I can share the Google Doc with you? Thanks!

**Comment by jsantell** [comment]
@kentcdodds just catching up on holiday mail! Sorry for the delay
- Jordan Santell
- github name at mozilla dot com
- @jsantell
- https://avatars1.githubusercontent.com/u/641267?v=3&s=460

**Comment by kentcdodds** [comment]
You're good. Thanks Jordan. Looking forward to [the show](jsair.io/ff-react-redux)

**Comment by jlongster** [comment]
@kentcdodds the gdoc you shared, are we supposed to fill it out with some initial content we think we could talk about?

**Comment by kentcdodds** [comment]
You definitely can if you'd like. Sorry, I don't think I gave you my normal spiel when I shared it with you:

> Hey there! This is the JavaScript Air show Google Doc. A few things to note:
> - The Hangout URL at the top is where you'll go to join the hangout for the show
> - Please look at the pre-show section before the show
> - The #main-content section is where we'll put stuff we want to talk about. This is not a scripted show. It's just a guide for our conversation. Feel free to add/remove/modify any of that.
> - If you want this event added to your calendar, click the link at the top and RSVP to the event.
> 
> Looking forward to the show!

Let me know if you have any more questions. Looking forward to the show next week :-)
