### ISSUE TITLE
Add discus to the episode page.

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#23]
Hey @alexbooker. Wanna take a look at this?

**Comment by gemmadlou** [comment]
+1 (for disqus)

**Comment by rajasekarm** [comment]
@kentcdodds  do we have an account on discus, I can make it on the site.

**Comment by kentcdodds** [comment]
Feel free to do everything but leave the disqus  ID blank and I'll fill it in when I merge. Sound good? Thanks!

**Comment by kentcdodds** [comment]
We have YouTube Live chat now. Don't need this anymore.
