### ISSUE TITLE
Swap Icon Fonts with SVG

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#25]
Perf, a11y, etc. etc. etc. cc/ @alexbooker

**Comment by awolf** [comment]
@kentcdodds has this been completed with the recent site redesign.? If not, what SVG's do we need?

**Comment by kentcdodds** [comment]
I think it's been fixed with the redesign merge. Do you wanna double check around the site and report back please? :-)

**Comment by awolf** [comment]
Will do.

**Comment by bookercodes** [comment]
@awolf The confetti images still need optimizing. Can you please do this or suggest a tool to use? Thanks.

**Comment by awolf** [comment]
I will do it tonight.
