### ISSUE TITLE
Panelist Twitter Links Are Broken

### ISSUE THREAD

**Issue by bookercodes** [javascriptair/site#27]
We noticed that the _panelists_ Twitter links are broke: 

![](https://i.imgur.com/gKn2zUH.png)

As you can see in the above screenshot, the problem stems from the fact that the anchor elements do not have `href` attributes.

I did some investigation, and the problem is this:

The [`Person` component](https://github.com/javascriptair/site/blob/14d0465b7c6424e41f2cb4bebd6e91ae9fea3260/src/components/person.js#L5) expects a `link` argument:

``` javascript
function Person({twitter, link, name, imgSrc}) {
...
```

... However, [panelists](https://github.com/javascriptair/site/blob/14d0465b7c6424e41f2cb4bebd6e91ae9fea3260/resources/panelists/index.js#L3) do not have links defined:

``` javascript
const panelists = sortPeople([
  {name: 'Dan Abramov', twitter: 'dan_abramov', startDate: '2015-12-09'},
  {name: 'Brian Lonsdorf', twitter: 'drboolean', startDate: '2015-12-09'},
...
```

... As such, the `Person` component is passed `undefined` for the `link` argument, and React omits the `href` attribute value. 

You might be asking _"So, why does the `Person` component work everywhere else?"_. The answer -  I _think_ - is that the other components somehow call the [`getEpisodeData` function](https://github.com/javascriptair/site/blob/14d0465b7c6424e41f2cb4bebd6e91ae9fea3260/shared/get-episode-data.js#L14), which populates the `link` property with a Twitter handle _if_ no `link` property is defined: 

``` javascript
function getEpisodeData(episodePath) {
...
guest = {
      imgSrc: `/episodes/${date}/${guest.twitter}.png`,
      link: `https://twitter.com/${guest.twitter}`,
      links: [],
      tips: [],
      picks: [],
      ...guest, // this line overwrites "link" if the guest has a truthy "link" value
    }
...
```

I guess you added this concept of a `link` in case a panelist or guest does not have a Twitter handle...?

I think it would be quite easy to apply a dirty fix, but instead I would rather confer wtih you about a proper solution. What are your thoughts?

**Comment by kentcdodds** [comment]
Thanks for researching that! This was definitely due to a refactor issue. I think the best place to populate the `link` attribute for panelists would be [here](https://github.com/javascriptair/site/blob/master/resources/panelists/index.js#L14-L16).

The host is hard-coded and we could just add a link [here](https://github.com/javascriptair/site/blob/master/src/pages/home/sections/host.js#L11). What do you think?

**Comment by bookercodes** [comment]
@kentcdodds If you're happy with that, then sure. I'll get on that now.

**Comment by kentcdodds** [comment]
Thanks for fixing this!
