### ISSUE TITLE
Learning and Developing JavaScript

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#3]
@getify originally thought this idea [here](https://twitter.com/getify/status/665985684096876544)

> hey @ashleygwilliams i think you and i should hop on some podcast (whichever one!) and chat about learning and developing and all that jazz. :)

(changed @ mention from twitter to github)

I think this would be a pretty sweet second show. Thoughts?

**Comment by ashleygwilliams** [comment]
hi! yes this is great idea. how do we proceed?

**Comment by kentcdodds** [comment]
Awesome! How's the 16th of December at [12:00 CST](http://www.thetimezoneconverter.com/)? Does that work for you too @getify?

**Comment by ashleygwilliams** [comment]
should work for me, but i can't confirm til i have booked my travel from seattle to SF (will be either that morning or the evening before ideally!)

**Comment by kentcdodds** [comment]
Got just about everything set up. @ashleygwilliams, would you prefer that I use your Twitter or github profile for the website? Also, @getify, I'd like to confirm with you that you'll be able to make this show since you'll technically be a guest on this one :-)

**Comment by getify** [comment]
Yes I can be there. :)

**Comment by kentcdodds** [comment]
@ashleygwilliams, could you get me a Google+ url for you? I'd like to +mention you on the Google+ event :-)

Also, please see [the JavaScript Air Guest Instructions](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing) and let me know if you have any questions!

**Comment by ashleygwilliams** [comment]
i don't really have/use google+ but this is me: https://plus.google.com/u/0/102650521771085125664
