### ISSUE TITLE
Forward Web Summit

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#32]
We may be able to do a live show at Forward Web summit with @DrBoolean, @getify, and anyone else who will be there. Thoughts? Still confirming with the forward team, but I'm sure we could do it.

**Comment by getify** [comment]
I'm down for it. :)

**Comment by DrBoolean** [comment]
Tyler should be there too. I can get a free ticket for anyone else if they want to come along.

**Comment by kentcdodds** [comment]
@DrBoolean, could you ensure that we have a place to actually do this. I still haven't heard back from Forward as to whether they're cool with us doing this.

**Comment by DrBoolean** [comment]
Yep!

**Comment by kentcdodds** [comment]
@DrBoolean, can you tell me what time it will be and if it'll definitely be on the 10th?

**Comment by tylermcginnis** [comment]
:+1:

**Comment by kentcdodds** [comment]
So the show's up on the site (http://jsair.io/forward) (@DrBoolean, let me know if the time needs to be changed). Any way we could get Forward to blast this out? They could use our tweet image:

![tweet](https://cloud.githubusercontent.com/assets/1500684/12124721/47a7c534-b3a4-11e5-8512-c1997ccc3a9d.png)
