### ISSUE TITLE
JavaScript Utils & Lodash

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#40]
**Title:** JavaScript Utils & Lodash

**Description:** Lodash v4 had been released (by the time this episode happens). This JavaScript library of utilities is one of the most widely used utility belts of the enormous JavaScript ecosystem. We're going to talk with John, the mastermind behind this utility (and fork of underscore) about his experience building such a ubiquitous tool and what it can do for you.

**Potential guest(s):** @jdalton

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md). Thanks!

**Comment by kentcdodds** [comment]
Also, @jdalton, please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). I only need your email address though. I have everything else. Hopefully the doc will give you an idea of what to expect for the show :-)

Thanks!

**Comment by jdalton** [comment]
I'm interested in being a guest though I'll be heads down prepping for the Tues (Jan 12th) release.

**Comment by kentcdodds** [comment]
You're good. We're scheduled out a ways. How does March 2nd sound?

**Comment by jdalton** [comment]
Sounds great!
