### ISSUE TITLE
live @ ng-conf

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#42]
Details forthcoming

**Comment by kentcdodds** [comment]
Hello @samccone, @juleskremer, @ocombe, @alyssamichelle, @Yonet, @teropa, @Hendrixer, @johnpapa, and @Brocco! You've been invited to join us **live** _and_ **on site** for the JavaScript Air ng-conf show!

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. This particular show will be **live** _and_ **on site** at ng-conf. For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

**Note:** This is a unique show. We've had a few on-site conference shows in the past and generally we have several guests come one/two at a time for 5-10 minutes each throughout the show. A good example of this is our on-site show at [React Conf](http://jsair.io/react-conf).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by samccone** [comment]
:tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: 
:tangerine: samuel john saccone
:tangerine: samccone <at> googlemail :diamond_shape_with_a_dot_inside: 
:tangerine: @samccone
:tangerine: 
:tangerine: THANK YOU KENT :space_invader: 
:tangerine: 
:tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine:

**Comment by teropa** [comment]
Tero Parviainen
tero@teropa.info
teropa

**Comment by Brocco** [comment]
Mike Brocchi
mbrocchi@gmail.com
@brocco

**Comment by juleskremer** [comment]
Jules Kremer
juleskremer@gmail.com
@jules_kremer

**Comment by johnpapa** [comment]
John@johnpapa.net@John_PapaJohn Papa

```
_____________________________
```

**Comment by Yonet** [comment]
Aysegul Yonet
aysegulyonet@gmail.com
@AysegulYonet

On Wed, Apr 27, 2016 at 10:44 AM, John Papa notifications@github.com
wrote:

> John@johnpapa.net@John_PapaJohn Papa
> 
> ---
> 
> From: Kent C. Dodds notifications@github.com
> Sent: Wednesday, April 27, 2016 12:49 PM
> Subject: Re: [javascriptair/site] live @ ng-conf (#42)
> To: javascriptair/site site@noreply.github.com
> Cc: John Papa john@johnpapa.net, Mention mention@noreply.github.com
> 
> Hello @samccone, @juleskremer, @ocombe, @alyssamichelle, @Yonet, @teropa,
> @Hendrixer, @johnpapa, and @Brocco! You've been invited to join us live and
> on site for the JavaScript Air ng-conf show!
> 
> If you haven't heard of JavaScript Air before, it's a live broadcast
> podcast all about JavaScript. This particular show will be live and on site
> at ng-conf. For more information about being a guest, see this Google Doc.
> Note: we also have and enforce a Code of Conduct for the show and guests
> have nothing but great things to say about their experience on the show.
> 
> Note: This is a unique show. We've had a few on-site conference shows in
> the past and generally we have several guests come one/two at a time for
> 5-10 minutes each throughout the show. A good example of this is our
> on-site show at React Conf.
> 
> If you're interested, I'll need a little information from you for the
> website. Episode planning happens on the GitHub repo issues. Please comment
> on your episode’s issue with the following information (if you’d prefer,
> you can email this info to javascriptair@gmail.com):Your name (as you
> want it on the site)An email address to share a Google Doc with youYour
> twitter handle
> 
> Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/javascriptair/site/issues/42#issuecomment-215167656

## 

Ayşegül

linkedIn/aysegulyonet http://www.linkedin.com/in/aysegulyonet/

   -

**Comment by alyssamichelle** [comment]
❤️ 
Alyssa Nicoll
mail@alyssanicoll.com
@AlyssaNicoll
❤️

**Comment by kentcdodds** [comment]
I should mention a few things:
1. The show starts at 2:00 (local time)
2. I'll put together a schedule before the show for ya'll and send that out in a Google Doc.
3. You'll be expected to show up 5 minutes before your start time and someone will tell you when to come on.
4. You'll get more info about exactly where this will be as I find out myself :-)

Thanks! Please let me know if you have any questions :-)

**Comment by joeeames** [comment]
It's in the Embassy room, which is on the 3rd floor, right next to the hack room

**Comment by kentcdodds** [comment]
Just realized that the fair day is on Thursday (correct @joeeames?). I'll be updating the website (I thought it was on Wednesday). Let me know if this is an issue for anyone.

**Comment by joeeames** [comment]
yes, Thursday. Sorry I didn't double check the day you had noted.

**Comment by Hendrixer** [comment]
Scott Moss
willscottmoss@gmail.com
scotups
