### ISSUE TITLE
JavaScript Air: Live and on-site at The Strange Loop

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#46]
:tada: http://www.thestrangeloop.com/

**Comment by DrBoolean** [comment]
+1, +1 a million times +1

**Comment by kentcdodds** [comment]
Hello friends! If you're @ mentioned on this issue (or I directed you to this issue) then you're invited to join me and @DrBoolean for ~30 minutes on Saturday (tomorrow) at The Strange Loop during lunch to chat about the conference and the topic of your talk/workshop! JavaScript Air is a live video broadcast/podcast for programmers. We focus on JavaScript, the web platform, and community. If you want to see what it's like, check out [this show](http://jsair.io/react-rally) we had at React Rally!

For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

Please let me know if you're interested and I'll be in touch with more info.

@bonniee, @inconshreveable, @gcrev93, Valerie Aurora (can't find github username)

**Comment by kentcdodds** [comment]
Sorry! I mistakenly said:

> Friday (tomorrow)

When I meant:

> Saturday (tomorrow)

It will definitely be Saturday, September 16th, 2016. I'll hope to have you at the room at 11:50ish and we'll be done by 12:30. Thanks!

**Comment by bonniee** [comment]
@kentcdodds I'm in.
name: Bonnie Eisenman
email: bonnie.eisenman@gmail.com
twitter: @brindelle

**Comment by kentcdodds** [comment]
I'd also like to invite @PaulKinlan!

**Comment by PaulKinlan** [comment]
Awesome

**Comment by gcrev93** [comment]
This sounds fun:) 
Name: Gabrielle Crevecoeur
Twitter: @nowayshecodes
Email: gacreve@microsoft.com

**Comment by kentcdodds** [comment]
Y'all should have received an email with an update for the calendar event with info about how to get to the Performer's Lounge where we'll be doing the show. Let me know if you have any questions!

**Comment by PaulKinlan** [comment]
Didn't realise I had to drop in information

Name: Paul Kinlan
Twitter: @Paul_Kinlan
Email: paulkinlan@google.com

**Comment by PaulKinlan** [comment]
BTW, awesome video of directions, I have one problem.  Where is the peabody lounge?

**Comment by kentcdodds** [comment]
Thanks Paul, you're good. I found your info via my normal stalking mechanisms (Google) :)

The Peabody Lounge is to the left of the Theater on the 2nd floor. I'm going there now to grab my food.
