### ISSUE TITLE
AVA

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#47]
I'd love to have @jamestalmage, @vdemedes, and @novemberborn on JavaScript Air to talk about the AVA framework (sadly @sindresorhus will not be joining us :disappointed:).

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you all could please comment on this issue about whether you're interested in coming on to talk about AVA and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md). Here are the next three available slots:
- 2016-03-23
- 2016-03-30
- 2016-04-06

**Comment by jamestalmage** [comment]
I'm in. Any of those dates should work for me.

James Talmage
https://twitter.com/jamestalmage
https://plus.google.com/u/0/+JamesTalmageR
Just use my twitter pic.

**Comment by kentcdodds** [comment]
Awesome! I'm leaning toward the 23rd. Does that work for you @vdemedes and @novemberborn?

**Comment by novemberborn** [comment]
Neat! 23rd would be fine.

Mark Wubben
https://twitter.com/novemberborn
https://plus.google.com/+MarkWubben
https://github.com/novemberborn/novemberborn.net/blob/2715eb1c21125dcaedec99e0d53b8c66cd22e744/static/rowing.jpg

**Comment by vadimdemedes** [comment]
Let's see what happens, this is frightening, haha! I'm in, 23rd works for me as well. 

Vadim Demedes
https://twitter.com/vdemedes
https://plus.google.com/114023635741969116976
https://pbs.twimg.com/profile_images/685421313117302784/sImpi3K_.jpg

**Comment by jamestalmage** [comment]
@kentcdodds - How long is the show? I am listening to the Babel episode now, 69 minutes! Are we going to have enough to talk about? Do we need to outline the major talking points ahead of time.

**Comment by kentcdodds** [comment]
Great everyone! I'll get you on the schedule!

The show is supposed to be 60 minutes. I've been doing better at keeping to that time that recently. We'll totally have plenty to talk about. I'll set up a Google Doc with all the relevant information for the show and we can fill it with subjects to discuss. Generally we have about 45 minutes to talk about stuff with announcements and the tips & picks section.

Looking forward to it!

**Comment by jamestalmage** [comment]
@sindresorhus should come lurk on the call anyways (If for no other reason than to IM me angry emoji when I say something stupid).

**Comment by kentcdodds** [comment]
You know, @kittens said no when I invited him to the Babel show, but jumped on mid-show. It was a fun surprise :-)

**Comment by kentcdodds** [comment]
@novemberborn, could you get me your email address? I need to share a Google Doc with you :-)

**Comment by kentcdodds** [comment]
@jamestalmage and @vdemedes, you should have received a Google doc from me just a moment ago. Let me know if you didn't :-)

**Comment by vadimdemedes** [comment]
@kentcdodds filled out my tips & picks, excuse me for doing it so late!

**Comment by kentcdodds** [comment]
No worries. Many people don't do it until the day of :-)
