### ISSUE TITLE
Live at KCDC

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#48]
More info to come

**Comment by kentcdodds** [comment]
Hello @coryhouse, @coridrew, @lyndseypadget, @matthewrenze, Eric Lee (can't find GitHub username), @taylonr, @jessitron, @jayharris, and @joeandaverde! You've been invited to join us **live** _and_ **on site** for the JavaScript Air KCDC show!

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. This particular show will be **live** _and_ **on site** at KCDC. For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

**Note:** This is a unique show. We've had a few on-site conference shows in the past and generally we have several guests come one/two at a time for 5-10 minutes each throughout the show. A good example of this is our on-site show at [ng-conf](http://jsair.io/ng-conf).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle

Thanks!

**Comment by jessitron** [comment]
sorry, I have to catch a train home on Friday. Won't be around. Cool that you're doing this though!

**Comment by kentcdodds** [comment]
@jessitron, sounds good. You'll be missed! Looking forward to seeing you at the conference!

**Comment by kentcdodds** [comment]
Oh, I should have mentioned, the plan is to have it during lunch time on Friday.

**Comment by coryhouse** [comment]
Cory House
@housecor
housecor@gmail.com

Excited to take part! Thanks for inviting me!

**Comment by taylonr** [comment]
Nate Taylor
@taylonr
taylonr@gmail.com

This seems awesome. Humbled to be on this list.

**Comment by dynajoe** [comment]
Sounds fun!

Joe Andaverde
@joeandaverde
joe.andaverde@gmail.com

May I also recommend @jonathanfmills
