### ISSUE TITLE
JavaScript Frameworks: Angular

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#49]
cc @mhevery, @igorminar, and @bradlygreen

Looks like the show will be April 6th!

Really looking forward to this show! I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Don't worry about sending me anything. I have everything for you :-)

Thanks!

**Comment by mhevery** [comment]
Looking forward to it.
