### ISSUE TITLE
Invert order of past episodes list

### ISSUE THREAD

**Issue by sapegin** [javascriptair/site#50]
I think it’s more common to show more recent episodes/posts/whatever first in this kind of lists. And since you removed dates it the new design it’s harder to undrestand that the list is reversed.

**Comment by kentcdodds** [comment]
You make great points! What if we add the episode index next to the title? With that I'd be fine with either approach.

**Comment by kentcdodds** [comment]
Thoughts @alexbooker, @Connorelsea, @awolf?

**Comment by sapegin** [comment]
Not sure. What do you think is more desired for the user: recent episodes or first episodes?

**Comment by kentcdodds** [comment]
Good question to ask! I'm mostly interested in ease of finding the episode they're looking for. Probably recent episodes first makes the most sense...

**Comment by awolf** [comment]
Recent to first is what I would expect.

**Comment by kentcdodds** [comment]
Awesome. A PR to fix this would be pretty simple. Anyone wanna [makeapullrequest.com](http://makeapullrequest.com)?

Here's where you'd make your changes: https://github.com/javascriptair/site/blob/f98a36b2a227259baab38de4ae819137e8cc6861/src/pages/home/sections/episodes/episodes.js#L16

Probably just a matter of telling lodash to reverse the sort order :-)

**Comment by kentcdodds** [comment]
Also, you may want to make a change to [this function](https://github.com/javascriptair/site/blob/f98a36b2a227259baab38de4ae819137e8cc6861/src/pages/home/sections/episodes/episodes.js#L74) to be able to add the episode index (but only for PastEpisodes, not for FutureEpisodes). That will be a little more of a challenge.

Remember, our first episode is episode `0` :-)

**Comment by bookercodes** [comment]
@sotojuan said she'll/he'll do it: https://twitter.com/_hooan/status/709447420086775810.
