### ISSUE TITLE
fix line height in "Past Episodes" section

### ISSUE THREAD

**Issue by da-vaibhav** [javascriptair/site#52]
![screen shot 2016-03-15 at 1 06 19 am](https://cloud.githubusercontent.com/assets/1468518/13757424/5e75aa42-ea4a-11e5-9625-60a3c5d35698.png)
the line which spans to multiple lines (3rd one) has very little distance from the text above it

**Comment by kentcdodds** [comment]
Agreed! Probably a simple css fix. Wanna [makeapullrequest.com](http://makeapullrequest.com)? Right now the CSS stuff is [here](https://github.com/javascriptair/site/tree/f98a36b2a227259baab38de4ae819137e8cc6861/resources/css)

**Comment by da-vaibhav** [comment]
sure, I am on it. Thanks.
