### ISSUE TITLE
word baseline is overlapped by background color of next section

### ISSUE THREAD

**Issue by da-vaibhav** [javascriptair/site#53]
observe the letter P in 'sponsors' text whose baseline part is overlapped when hovering on the section which is next to it.
This happens in all 3 sponsor sections.
![screen shot 2016-03-15 at 1 18 03 am](https://cloud.githubusercontent.com/assets/1468518/13757956/e2d28470-ea4c-11e5-81ae-7a0ac68eddba.png)
on hover:
![screen shot 2016-03-15 at 1 28 34 am](https://cloud.githubusercontent.com/assets/1468518/13758039/503403e0-ea4d-11e5-9e8f-ae0bd2e6b332.png)

**Comment by kentcdodds** [comment]
Nice catch! PR for this is welcome too! Please include a screenshot with your PR if you would please :-)

Also, for your first PR, please add yourself to the contributors in the `data` folder :-)

**Comment by da-vaibhav** [comment]
yup, thanks :-)
