### ISSUE TITLE
Request: Make tagline a bit more descriptive

### ISSUE THREAD

**Issue by Connorelsea** [javascriptair/site#54]
Would be good for people looking to contribute or recruiters looking at contributors pages and wondering what it is.

![img_2016-03-14 15 52 48](https://cloud.githubusercontent.com/assets/1844458/13759559/d16b21ba-e9fc-11e5-9f47-e0cecde0714e.jpg)

**Comment by kentcdodds** [comment]
👍

**Comment by Connorelsea** [comment]
Awesome!

**Comment by kentcdodds** [comment]
<img width="375" alt="screen shot 2016-03-14 at 2 59 21 pm" src="https://cloud.githubusercontent.com/assets/1500684/13759775/5ce88abe-e9f5-11e5-9efd-577f04682263.png">

That's better :-)
