### ISSUE TITLE
Clearer image compressing instructions

### ISSUE THREAD

**Issue by sotojuan** [javascriptair/site#59]
It would be nice to add something like this [this section](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md#images):

> After you get your resized image (should have your original filename with "resized" in the middle), you can delete your original image and rename the compressed one to the original filename. Essentially, you're replacing the original with the compressed one.

Could be written a little less verbose, but you get the point. Can do this in a PR!

Alternatively, we can discuss changing the behavior of `imagina` to overwrite the original image.

**Comment by kentcdodds** [comment]
> Alternatively, we can discuss changing the behavior of imagina to overwrite the original image.

Yeah, the problem is that some people might actually use this tool on an image they have locally that they use for other stuff and wouldn't want the original to be impacted (think immutability :wink:). So I'm thinking probably just documenting the behavior is good. I'd appreciate a PR. Thanks!
