### ISSUE TITLE
Emoji in the title doesn't render

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#61]
See [javascriptair.com](http://javascriptair.com) right now:

<img width="988" alt="screen shot 2016-03-15 at 2 32 35 pm" src="https://cloud.githubusercontent.com/assets/1500684/13793494/b8d2f388-eabc-11e5-91e0-5b97da41ca00.png">

Anyone have any ideas? This worked before the redesign was merged if that's helpful.

**Comment by bookercodes** [comment]
I cannot reproduce this locally.

In Chrome with [Emoji Keyboard](https://chrome.google.com/webstore/detail/emoji-keyboard-2016-by-em/ipdjnhgkpapgippgcgkfcbpdpcgifncb) installed, this is what I see:

![](http://i.imgur.com/dMIxS9G.png)

In Firefox with no extensions installed, this is what I see:

![](http://i.imgur.com/WO1JAKl.png)

I am running Arch Linux.

**Comment by kentcdodds** [comment]
I should say this is on Mac. Works fine on my phone.

**Comment by da-vaibhav** [comment]
looks fine on Firefox. I think its problem only with chrome on mac.

**Comment by da-vaibhav** [comment]
here is the solution I found on [stackoverflow](http://stackoverflow.com/questions/35395708/unicode-emojis-not-showing-on-chrome), its the problem with value of font-weight property. Setting it bold renders it invisible.

**Comment by kuzzmi** [comment]
Yeah, it appears to be an issue with making Emojis bold in Chrome on Mac, I've just tested on my Mac with Chrome DevTools.

**Comment by kentcdodds** [comment]
Yep! That's the issue @da-vaibhav. I'll look into fixing it...

<img width="1053" alt="screen shot 2016-03-16 at 1 05 01 pm" src="https://cloud.githubusercontent.com/assets/1500684/13825355/c3fbe1b4-eb77-11e5-831b-e8e9617e6d07.png">

**Comment by kentcdodds** [comment]
A fix (hopefully) is building now. Thanks @da-vaibhav! Probably could/should have made that a first-timers-only issue... `¯\_(ツ)_/¯`

**Comment by kentcdodds** [comment]
:sweat_smile: this is why I should have done this locally and tested it out first...

<img width="1105" alt="screen shot 2016-03-16 at 1 09 46 pm" src="https://cloud.githubusercontent.com/assets/1500684/13825494/6982189c-eb78-11e5-9346-ec20f9e38d44.png">

![muppets-annoyed-vwI4mYEHP8k0w](https://camo.githubusercontent.com/4acbc70170a591d6f6298f297293d244d3b68456/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f767749346d59454850386b30772f67697068792e676966)

**Comment by Ekthelion** [comment]
yup, on win10:
![capture](https://cloud.githubusercontent.com/assets/2337180/13825569/65dd71c4-ebb3-11e5-847f-bd357ff847d2.PNG)

**Comment by da-vaibhav** [comment]
:sob:

**Comment by kentcdodds** [comment]
Fixing now. I could have sworn it was OK to use markdown for the title... hee hee

**Comment by kentcdodds** [comment]
Alright, just pushed a real fix. How embarrassing! Should be up in a minute.

**Comment by Ekthelion** [comment]
works!

**Comment by kentcdodds** [comment]
![day-subreddit-msKNSs8rmJ5m](https://camo.githubusercontent.com/f53ccacdd8379facfcb4bd8333417ca9e27f6b0a/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f6d734b4e537338726d4a356d2f67697068792e676966)

**Comment by da-vaibhav** [comment]
this fix actually caused another change. the text inside anchor tags in the past episodes section is wrapped inside `p` tag, which caused line breaks for all the links. all the participants' names are on next lines now. 
![screen shot 2016-03-17 at 01 26 20](https://cloud.githubusercontent.com/assets/1468518/13826783/4c6a61b2-ebdf-11e5-94ce-d6eef8365c84.png)

![screen shot 2016-03-17 at 01 25 58](https://cloud.githubusercontent.com/assets/1468518/13826784/4c6ee9a8-ebdf-11e5-88be-58b3e9226001.png)

**Comment by kentcdodds** [comment]
Ah... :sweat_smile: I thought something looked different... Pushing a fix now. Thanks!
