### ISSUE TITLE
Bad formatting in Episode 001's Links, Tips, and Picks

### ISSUE THREAD

**Issue by sotojuan** [javascriptair/site#62]
Just wondering if [this](https://github.com/javascriptair/site/blob/master/episodes/2015-12-16/index.js#L20) formatting of two Markdown links is intentional. Looks like this on the site:

<img width="555" alt="screen shot 2016-03-16 at 4 15 27 pm" src="https://cloud.githubusercontent.com/assets/8217766/13828941/553f2d24-eb92-11e5-9649-a14673b5ede0.png">

**Comment by kentcdodds** [comment]
Nope! Please feel free to PR a fix if you'd like :-)
