### ISSUE TITLE
Redesign episode page

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#66]
Make it consistent with our homepage design. Let's chat :-)

**Comment by jpoo90** [comment]
Hi @kentcdodds I can help :bowtie:

**Comment by Connorelsea** [comment]
I had some ideas to make the episode page share a ton of code with the episode cards already on the home page and had planned on implanting that. I can take this one if that's okay. And I am also working on a mockup for the global title right now.

**Comment by jpoo90** [comment]
@Connorelsea Cool, go ahead ! You have already made progress here.

**Comment by Connorelsea** [comment]
@jpoo90 We can definitely work together if you want! And there are other pages to be done as well that are up for grabs. Whichever way works with you is good!

**Comment by jpoo90** [comment]
@Connorelsea We can definitely work together. Since you've been working here for a while I'd like your suggestions. Are the other pages co-related too ?

**Comment by Connorelsea** [comment]
Currently I am mocking up a global header for each page to keep them consistent (about to open a new issue after that) and then it is basically creative freedom for the content of each page as long as it fits with the theme of the home page.
