### ISSUE TITLE
Design and implement global header for non-index pages

### ISSUE THREAD

**Issue by Connorelsea** [javascriptair/site#68]
Here is the design I have created for the global header. If this is good, let me know and I can begin implementation. The "View Next Show" box would only appear on the episodes page. On other pages it would simply not appear. Maybe something else can go there on other pages, but I have no ideas for that yet.

<img width="576" alt="globalheader" src="https://cloud.githubusercontent.com/assets/1844458/13832513/dd146c74-ebaa-11e5-949c-2c9191569e38.png">

**Comment by kentcdodds** [comment]
:+1: good first pass. A few things I'm not in love with. Having the confetti behind the logo looks funny. I like it on the right side though.

Not sure about what should go on the nav... What do others think?

**Comment by Connorelsea** [comment]
Ah yeah forgot to mention that the nav links I wasn't sure about. Mostly just getting a pass on the design so then we can discuss specific content. So let me know what the specific nav links should be.

**Comment by rajasekarm** [comment]
@Connorelsea  can you finalize the design and share me the psd. I will start implementing it. Thanks.

**Comment by Connorelsea** [comment]
I had already started implementing it on my fork after Kent gave his feedback. I'm in class right now, but I'll work something out where we can work together whenever I'm off.

**Comment by rajasekarm** [comment]
yup sure. @kentcdodds  do we have any common chat, so that we can discuss it over there rather than in comments??

**Comment by kentcdodds** [comment]
We do now :-) https://gitter.im/javascriptair/site

**Comment by kentcdodds** [comment]
Turns out this isn't mobile ready :laughing: :smile:
![screenshot_20160330-071931](https://cloud.githubusercontent.com/assets/1500684/14143358/0f041246-f648-11e5-8476-195a5f1b3959.png)
