### ISSUE TITLE
Internet of Things with JavaScript

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#72]
**Title:** Internet of Things with JavaScript

**Description:** The world is becoming more and more interconnected with more devices joining and communicating on the network every day. The space of hardware hacking is exciting! It's becoming even more welcoming to developers as the barrier to entry has been decreased significantly with JavaScript.

For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

Our show is each week on Wednesday at [12:00 CT](http://www.thetimezoneconverter.com/). Here's [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md) of available dates.

I've already gotten a response from @nodebotanist and @gelicia. Sounds like good dates for them are:
- 2016-04-20  
- 2016-04-27

@rwaldron, do either of those dates work for you?

Also, @phoddie, someone recommended that I reach out to you and invite you on this show as well. Would you like to join? If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. I hope you can join us!

Thanks!

**Comment by phoddie** [comment]
Hello --

Yes, I can join on 4/20.

-- Peter

**Comment by kentcdodds** [comment]
Awesome @phoddie! And @rwaldron? Can you make it on the 20th?

**Comment by kentcdodds** [comment]
I'm going to go ahead and put this on the 20th. @rwaldron, I hope you can make it :-) But no pressure!

@nodebotanist, @gelicia, and @phoddie, looking forward to having you on the show! I'll be in touch with you later here :-) Let me know if you have any questions until then :D

**Comment by phoddie** [comment]
Here's the requested info:
   Name: Peter Hoddie
   Twitter: @phoddie (and @kinoma)
   Google+ profile: None! Please use Kinoma’s profile: https://plus.google.com/+KinomaMarvell/posts.
   Profile image: https://avatars0.githubusercontent.com/u/6856458

**Comment by kentcdodds** [comment]
Thanks!

**Comment by andycarle** [comment]
Hi folks, I'm tagging in for Peter Hoddie tomorrow. Here's my info:

Name: Andy Carle
Twitter: @PrototypingAndy and @kinoma
Google+: Nope! But Kinoma does have one: https://plus.google.com/+KinomaMarvell
Profile image: https://avatars1.githubusercontent.com/u/1427817?v=3&s=460

**Comment by kentcdodds** [comment]
Thanks for stepping in @andycarle. Looking forward to hearing your perspective. The site's been updated. See ya'll tomorrow!
