### ISSUE TITLE
JavaScript Frameworks: Vue.js

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#75]
Planning on having a show with @yyx990803 about Vue.js on the 30th of March. :+1:

@yyx990803, if you feel anyone else could contribute well to the conversation, that'd be great to @ mention them here and invite them to join us :-)

**Comment by kentcdodds** [comment]
For the benefit of anyone @yyx990803 invites:

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Thanks!

**Comment by yyx990803** [comment]
@taylorotwell (author of Laravel) will be joining us on the show - bringing some perspective from "non-js-people" ;)

**Comment by kentcdodds** [comment]
That'd be fantastic. I'll get @taylorotwell added to the site. Thanks!
