### ISSUE TITLE
JavaScript Frameworks: Ember

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#76]
Let's get Ember in on this JavaScript Frameworks thing.

Planning on having the show on the 27th of April at [12:00 CDT](http://www.thetimezoneconverter.com/).

@wycats and @tomdale are still both invited to this show. @mixonic has agreed to come on and I'm waiting on one or two more people to let me know.

I'll update ya'll on this issue when I have more info. Let me know if you have any questions in the meantime :-)

**Comment by kentcdodds** [comment]
Hey @mixonic, I had a show fall through for the 13th of April. Is there any chance you could join us on that day instead?

**Comment by kentcdodds** [comment]
We're going to stick with the 27th of April :+1:

Really looking forward to this show! I need a few things from all guests to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle
- Your profile picture at least 180x180px in size (or you can just tell me to use your twitter/github profile picture)

Thanks!

**Comment by kentcdodds** [comment]
@mixonic, don't worry about providing your info, I've already got you on the site :-)

**Comment by GavinJoyce** [comment]
@kentcdodds as I mentioned [on twitter](https://twitter.com/gavinjoyce/status/718144963431829504), I'd be happy to chat if you're interested in hearing how Ember.js has contributed to our success and rapid growth at Intercom over the past 30 months.

**Comment by kentcdodds** [comment]
Awesome! Feel free to leave your info as instructed above @GavinJoyce :-) Thanks!

**Comment by GavinJoyce** [comment]
Email sent, thanks

**Comment by mixonic** [comment]
Thanks @kentcdodds, looking forward to it :heart_eyes: :heart_eyes:

**Comment by rwjblue** [comment]
Just sent email, hoping to join in also (if it isn't too late)...
