### ISSUE TITLE
Automation: Audio

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#78]
I'd love to be able to have something like this:

```
podcastify-youtube-video i3ET71ZCW_E some/destination/file.mp3 --metadata artist-name="JavaScript Air" --metadata track-title="JavaScript Frameworks: Vue.js" --metadata album-title="JavaScript Air" --metadata track-number="16" --metadata year="2016" --metadata comments="Go to http://javascriptair.com to learn more."
```

Where `i3ET71ZCW_E` is the ID of a YouTube video and `some/destination/file.mp3` is where I want the output file to go and all those metadata things is used for the audio file's metadata (would prefer sane defaults and maybe a config file or something). What this command would do:
1. Get the audio from the video (probably by downloading the video and extracting the audio)
2. Convert the stereo output to mono (preserving both left and right, and just merging it to mono)
3. Normalize the audio
4. Save it as an optimized `mp3` file with the specified metadata properties.

This would save me a half an hour per week, which would be awesome.

Anyone wanna build this? I'd prefer if it were something I could hack on in JavaScript, but if you wanna build it, I don't care how you do it :-)

**Comment by sduquej** [comment]
This seems like a good existing option (it's written in Python): https://github.com/rg3/youtube-dl

**Comment by kentcdodds** [comment]
Thanks for the suggestion @sduquej! What do you think about [this one](https://libraries.io/npm/youtube-mp3-downloader) written in JavaScript?

**Comment by kentcdodds** [comment]
This is actually looking awesome. I've got a PR I'm preparing with most of the requirements. Will reference it here in a moment. Thanks @sduquej!

**Comment by kentcdodds** [comment]
Here's the first version: https://github.com/javascriptair/site/pull/81

**Comment by kentcdodds** [comment]
`npm run podcastify` :D
