### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#79]
**Title:** Progressive Web Apps

**Description:** A [Progressive Web App](https://developers.google.com/web/progressive-web-apps?hl=en) "uses modern web capabilities to deliver an app-like user experience. They evolve from pages in browser tabs to immersive, top-level apps, leveraging the web's low friction." The JavaScript Air website uses some of these techniques and technologies. Let’s learn about this awesome stuff!

**Potential guest(s):** @nolanlawson, @HenrikJoreteg, @jakearchibald, @slightlyoff

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md). Please note that having 4 guests is totally acceptable for this show because the more backgrounds/experiences the better. So if you can all make it that'd be awesome. Here are a few dates to consider:
- 2016-05-18
- 2016-05-25
- 2016-06-01

**Comment by HenrikJoreteg** [comment]
:wave: Most likely May 25 would be my best bet. I'm likely traveling both the other dates. My life is a bit crazy at the moment, I'm moving, doing a full time consulting gig, and having just sold my house will be homeless during this period :)

**Comment by nolanlawson** [comment]
May 25th works for me as well! Happy to co-guest-star with @HenrikJoreteg and anybody else who's interested. :)

**Comment by jennwrites** [comment]
:eyes: omg yasssssssss

**Comment by kentcdodds** [comment]
I'd also like to invite @AdaRoseEdwards to join us for the show! Please see the original comment and let me know if you're interested and if May 25th works for you as well :-)

**Comment by jakearchibald** [comment]
2016-06-01 is the only one of the three I can do, but I'm happy to skip it as everything is covered with the other guests

**Comment by kentcdodds** [comment]
@jakearchibald, sorry that you can't make it on the 25th. I want to make sure that we cover our bases on the perspectives we have on the show, so let's see what others say.

I'd also like to invite @wanderview from Mozilla and @addyosmani from Google to get those perspectives. I did talk with @slightlyoff at Fluent conf and he sounded less enthusiastic about showing up :-) Though you're definitely still invited Alex!

I think it'd be great if the final line up included @HenrikJoreteg, @nolanlawson, and @AdaRoseEdwards to get the user perspective and @wanderview, @addyosmani, and @slightlyoff to get the builder/vendor/advocate/etc. perspective that'd be great.

Let me know what you think and if you have any questions!

**Comment by AdaRoseCannon** [comment]
Yeah, i'd love to do it! May 25th should be fine.

**Comment by kentcdodds** [comment]
Really looking forward to this show! Still waiting to hear back from some of you. While we wait, I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle
- Your profile picture at least 180x180px in size (or you can just tell me to use your twitter/github profile picture)

Thanks!

**Comment by HenrikJoreteg** [comment]
Henrik Joreteg
hjoreteg@gmail.com
@HenrikJoreteg 
pics and such: http://bio.joreteg.com/

**Comment by AdaRoseCannon** [comment]
Ada Rose Edwards
ada.edwards@ft.com
@lady_ada_king
![image](https://cloud.githubusercontent.com/assets/4225330/14531076/b0535886-0210-11e6-8330-900f9e8256ae.png)

**Comment by wanderview** [comment]
I can't claim to be entertaining or knowledgeable, but I'd be happy to attend if its not too late.  Please feel free to use my info from twitter for now.  If I get a better picture I will send it along.  Thanks!

**Comment by kentcdodds** [comment]
Fantastic! Looking forward to having you on the show!
