### ISSUE TITLE
ES6 Show

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#8]
**Title Idea:** The features of ES6

**Idea:** The title is sort of self-explanitory

**Potential guest(s):** @rauschma, @bevacqua

**Comment by kentcdodds** [comment]
What do you all think? Are you interested?

**Comment by rauschma** [comment]
I just saw today’s edition. Well done!

My problem is that I’ve never been as busy as I am right now and that @bevacqua and I are already scheduled for an ES6 podcast on January 5. So for the next few months, I’ll have to decline (but you may already have covered the topic with today’s edition, anyway).

**Comment by kentcdodds** [comment]
Oh don't tell me the awesome people over at JavaScript Jabber got you first did they?! Haha, oh well, I'll enjoy that show for sure. I'll put this in the backlog and maybe have you on to talk about the features of ES7 in a month or two.

**Comment by bevacqua** [comment]
+1 to what Axel said, maybe later down the road ^^
