### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#82]
**Title:** webpack: JavaScript bundler

**Description:** webpack is an amazing bundler for frontend assets. For many people it has completely changed the game for their build pipeline, entirely replacing other build tools and task runners like grunt and gulp. Join us as we talk with the webpack team about this impressive piece of tech.

**Potential guest(s):** @sokra, @jhnns, @bebraw

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md). Thanks!

**Comment by bebraw** [comment]
Works for me.

**Comment by kentcdodds** [comment]
Great @bebraw! How about you @sokra and @jhnns? Would love to have all three of you on the show! Let me know how these dates work for you:
- 2016-05-18
- 2016-06-01
- 2016-06-08

**Comment by jhnns** [comment]
Cool! :tada: 

All dates work for me, with a small preference for the two latter ones. The only problem is that I have to get up that early (it's even worse for you @bebraw) :grin:

**Comment by bebraw** [comment]
@jhnns 12:00 Central Time should be 20:00 EEST. Even 00:00 wouldn't be too bad at 08:00. Did you mean the latter?

**Comment by jhnns** [comment]
Haha, yeah, I've entered 12.00 AM and didn't think a lot. 7:00 PM is ok, I'll probably be awake then :wink:

**Comment by kentcdodds** [comment]
Really looking forward to this show! I need a few things from you all to get things set up for the show. Please read the [guest FAQ](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit). Here's the most time intensive piece:

Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle
- Your profile picture at least 180x180px in size (or you can just tell me to use your twitter/github profile picture)

Thanks!

Also, @sokra, which of the dates work for you? I get the impression that this may be a little outside your comfort zone. Forgive me if this is an incorrect impression. I'd really like to have you on the show. If it helps, JavaScript Air has a great [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) which I, [the panelists](https://javascriptair.com/#panelists), and [guests](https://javascriptair.com/guests) are expected to abide by. And guests have nothing but great things to share about their experience on the show. Please let me know what I need to do to get you to come on the show (even if it means your video is turned off, seriously, whatever makes you comfortable enough to come on) :-)

**Comment by jhnns** [comment]
- Johannes Ewald
- johannes.ewald@peerigon.com
- [jhnnns](https://twitter.com/jhnnns) (it's three ns, because jhnns was already taken)
- Please use my Github profile picture

**Comment by bebraw** [comment]
- Juho Vepsäläinen
- bebraw@gmail.com
- [bebraw](twitter.com/bebraw)
- Twitter/GitHub profile picture would work

**Comment by kentcdodds** [comment]
Awesome, thanks guys. I'll wait to hear from @sokra whether he's interested and what dates work before actually scheduling. Looking forward to it!

**Comment by sokra** [comment]
All dates work for me.
- Tobias Koppers
- tobias.koppers@googlemail.com
- no twitter sorry
- GitHub profile picture

**Comment by kentcdodds** [comment]
Awesome!

So our guests for the show on the 13th of April had to cancel. Would you all be available on that day? Otherwise we can do the 1st of June.

**Comment by jhnns** [comment]
That would work for me too (with a small uncertainty because I'm on a train 2 hours before the show).

**Comment by bebraw** [comment]
If 13th of April works for Tobias, I'm in. I have an appointment there, but I can flex a bit.

**Comment by sokra** [comment]
Sorry 13th doesn't work for me...

**Comment by kentcdodds** [comment]
OK cool. June 1st it is then. Looking forward to it!

**Comment by jhnns** [comment]
Yay :tada:

**Comment by kentcdodds** [comment]
Would ya'll be interested in having @thelarkinn join the show as well? I think it's good to have more perspectives on the show and I believe you all know him already :-) Thoughts?

**Comment by bebraw** [comment]
Sure. 👍

**Comment by sokra** [comment]
:+1:

**Comment by kentcdodds** [comment]
Hey all! I have to really apologize for this, but is there any chance we could push this show out a week? That would put the show at [12:00 PM CDT](http://www.thetimezoneconverter.com/) on June 8th. Please let me know one way or another as soon as you're able. Thank you! And sorry!

**Comment by TheLarkInn** [comment]
I'm fine either way.

**Comment by bebraw** [comment]
Works for me.

**Comment by sokra** [comment]
yep

**Comment by jhnns** [comment]
Works for me too, no problem :)

**Comment by kentcdodds** [comment]
Alrighty, everything's been moved the the 8th. Thanks for working with me on this :) I didn't want to miss this show.
