### ISSUE TITLE
Reactive Programming in JavaScript

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#84]
**Title:** Reactive Programming in JavaScript

**Description:** Object oriented programming, functional programming, reactive programming, reactive functional programming. There are so many different ways to think about the system you're building and different design patterns to follow. Join us as we talk about reactive programming in JavaScript.

**Potential guest(s):** @staltz, @blesh, @mattpodwysocki, anyone else?

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing). Note: we also have and enforce a [Code of Conduct](https://github.com/javascriptair/CODE_OF_CONDUCT) for the show and guests have nothing but great things to say about their experience on the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the available dates on [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md).

Specifically, let me know if any of these dates work for you:
- 2016-04-13
- 2016-06-01
- 2016-06-08

In particular, I'd really like to do the 13th of April because that just opened up and there's not another opening until June, but let me know what works for you all!

If you're interested, I'll need a little information from you for the website. Episode planning happens on the GitHub repo issues. Please comment on your episode’s issue with the following information (if you’d prefer, you can email this info to [javascriptair@gmail.com](mailto:javascriptair@gmail.com)):
- Your name (as you want it on the site)
- An email address to share a Google Doc with you
- Your twitter handle
- Your profile picture at least 180x180px in size (or you can ask me to just use your github/twitter profile)

Thanks!

**Comment by staltz** [comment]
2016-04-13 works for me

> ```
> Your name (as you want it on the site)
> An email address to share a Google Doc with you
> Your twitter handle
> Your profile picture at least 180x180px in size (or you can ask me to just use your github/twitter profile)
> ```
- Andre Staltz
- andre`[dot]`staltz`[at]`gmail`[dot]`com
- `@andrestaltz`

![andre-budapest-square](https://cloud.githubusercontent.com/assets/90512/14254505/af0b2096-fa98-11e5-96ac-dc10fe85c326.jpg)

**Comment by benlesh** [comment]
April 13th works for me.

Ben Lesh
`ben[at]benlesh[dot]com`
`@benlesh`

image:
![http://i.imgur.com/jfv9elj.png](http://i.imgur.com/jfv9elj.png)

**Comment by kentcdodds** [comment]
Just pushed an update to the website with this info. @mattpodwysocki is still totally invited to join. Is there anyone else that we should have on the show? May be good to have someone who's not all in on RxJS :-)

**Comment by staltz** [comment]
Like JLongster :D

**Comment by mattpodwysocki** [comment]
@kentcdodds sorry, I've been on travel

**Comment by mattpodwysocki** [comment]
April 13th it is.

Matthew Podwysocki
`matthewp`[at]`microsoft`[dot]`com`
`@mattpodwysocki`

<img src="https://pbs.twimg.com/profile_images/506580998222381057/axNYv-3_.jpeg">
