### ISSUE TITLE
Add links, tips, and picks page

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#85]
Would be great to have a single place to go to find all the links, tips, and picks (like [these](https://github.com/javascriptair/site/blob/4102ad8adbff2757f5a8724bbc0ee6c26e8deb53/episodes/2016-03-30/index.js#L7-L20) which is rendered [here](https://javascriptair.com/episodes/2016-03-30/#show-notes) via [this component](https://github.com/javascriptair/site/blob/4102ad8adbff2757f5a8724bbc0ee6c26e8deb53/src/pages/episode/sections/show-notes/index.js#L8-L35)). Things to do to make this happen:
- [ ] Add a component for the root element for the page in [`src/pages`](https://github.com/javascriptair/site/tree/master/src/pages)
- [ ] Add a generator file in [`generate`](https://github.com/javascriptair/site/tree/master/generate)
- [ ] Add a script in `package.json` to build the page
- [ ] Update [the `build` script](https://github.com/javascriptair/site/blob/4102ad8adbff2757f5a8724bbc0ee6c26e8deb53/package.json#L17) to run your new script as well.

On the specific implementation details. You'll need to note that the links, tips, and picks are part of people "objects" which can be found in `guests`, `host`, and `panelists`. For getting things setup and getting the data you need, you can probably do something very similar to the `guests` page. Here are the relevant files:
- [`generate/guests.js`](https://github.com/javascriptair/site/blob/master/generate/guests.js)
- [`src/pages/guests/index.js`](https://github.com/javascriptair/site/blob/master/src/pages/guests/index.js)
- [`build` and `prebuild` scripts](https://github.com/javascriptair/site/blob/4102ad8adbff2757f5a8724bbc0ee6c26e8deb53/package.json#L10-L11)

One thing that you'll probably want to do that the guests page doesn't do yet is use the fancy [`Header` component](https://github.com/javascriptair/site/blob/master/src/components/header.js) like [this](https://github.com/javascriptair/site/blob/master/src/pages/contributors/index.js#L15).

Any help appreciated!

**Comment by timarney** [comment]
I'll take this on, assuming it's still of interest.

**Comment by kentcdodds** [comment]
Yes! Definitely still interested. Thank you :-)

**Comment by timarney** [comment]
For output I'm thinking of 

```
=============
Episode Name
=============
Person Name
Links
Tips
Picks
--
Person Name
Links
Tips
Picks
=============
Episode Name
=============
Person Name
...
```

Or did you have another output in mind?  

The page will get long over time but, good for a starter page.

Also should I put a link in the footer i.e. All Links, Tips, and Picks?
