### ISSUE TITLE
Add "tweet" link to episodes page

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#88]
I'd like to enable/encourage people to share the episode. I'd love to have a link toward the top of the episode page that's something like "tweet this" and it'll tweet something like:

Upcoming episode

> Watch "${episode.title}" live w/ ${episodeGuestTwitterHandlesOrNames} on ${episode.date} ${episode.shortUrl} ${randomAwesomeEmoji}

Past episode:

> Check out "${episode.title}" w/ ${episodeGuestTwitterHandlesOrNames} ${episode.shortUrl} ${randomAwesomeEmoji}
1. `randomAwesomeEmoji` could probably use something like [this](https://github.com/javascriptair/site/blob/087dd456c209ad39748185855fd03a659c6c19f2/other/get-up-tweet.js#L55-L66)
2. `episodeGuestTwitterHandlesOrNames` can use [`utils.displayListify`](https://github.com/javascriptair/site/blob/087dd456c209ad39748185855fd03a659c6c19f2/shared/utils.js#L34)
3. The code would probably hook in around [here](https://github.com/javascriptair/site/blob/087dd456c209ad39748185855fd03a659c6c19f2/src/pages/episode/sections/header/index.js#L34-L37)

Let me know if anyone wants to take this on :-D

**Comment by daltonamitchell** [comment]
If nobody gets to this by tomorrow, I'd be happy to help!

**Comment by sarbbottam** [comment]
You are faster by 16 seconds 😄

**Comment by daltonamitchell** [comment]
No worries @sarbbottam if you want to take this. I know I won't get to it until the AM. But if it's still open tomorrow I'm happy to lend a hand :)

**Comment by sarbbottam** [comment]
All yours, I wont be able to get on this before weekend.
