### ISSUE TITLE
Js and functional programming: the next stage

### ISSUE THREAD

**Issue by baptistemanson** [javascriptair/site#9]
**Title Idea:** Js and functional programming: the next stage

**Idea:** Functional programming have been greatly facilitated with ES6. Explore how prototyping can be further enhanced by using functional and immutable design patterns in JS.

**Potential guest(s):** @gaearon, @fogus

**Comment by kentcdodds** [comment]
👍 what do you all think?

**Comment by kentcdodds** [comment]
Hi @gaearon, @DrBoolean, and @fogus. I'd like to schedule this show for the 30th. Let me know if you'd be interested in joining as our guests for the show and if you're available on that day.

If you haven't heard of [JavaScript Air](http://javascriptair.com) before, it's a live broadcast podcast all about JavaScript. Shows happen every Wednesday at [12:00 Central Time](http://www.thetimezoneconverter.com/). For more information about being a guest, see [this Google Doc](https://docs.google.com/document/d/1Wlg5NxTkDX8k77TnCx4Rgm-nHQKr5pzwGKN81k90XKQ/edit?usp=sharing).

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and your availability (or unavailability) for the next available [slots](https://github.com/javascriptair/site/blob/master/other/schedule.md).

**Comment by DrBoolean** [comment]
I'm all about this episode. I can be available anytime

**Comment by gaearon** [comment]
I'll be happy to join.

**Comment by fogus** [comment]
Thank you for the offer, but I think that with @DrBoolean and @gaearon on the show anything that I would have to say would be redundant.  Therefore, I am happy to sit this one out and be a listener instead.  Enjoy!

**Comment by kentcdodds** [comment]
Technically @DrBoolean and @gaearon are panelists and would be on the show anyway. We appreciate having people with different backgrounds and perspectives, so you're more than welcome to attend. But if you'd rather not I understand :-) Happy Holidays!

**Comment by DrBoolean** [comment]
It would have been an honor :)

**Comment by pselle** [comment]
Would love to have @bodil on the show for a functional episode! @bodil, you interested?

**Comment by DrBoolean** [comment]
+1 on @bodil

**Comment by mzabriskie** [comment]
I think that @jessitron would be a great guest for this episode.

**Comment by kentcdodds** [comment]
Agreed. @bodil & @jessitron, what do you think? It's scheduled for 12:00 CST on the 30th.

**Comment by kentcdodds** [comment]
Sorry, let me back peddle for a second. How's your availability for February?

**Comment by kentcdodds** [comment]
More specifically, Wednesdays at 12:00 CST. See [the schedule](https://github.com/javascriptair/site/blob/master/other/schedule.md)
