### ISSUE TITLE
Fix calendar icon styling

### ISSUE THREAD

**Issue by kentcdodds** [javascriptair/site#91]
Anyone wanna investigate what's going on in Chrome for this? On hover over the calendar date, this is what I see (Chrome is wrong).

Chrome:

<img width="217" alt="chrome" src="https://cloud.githubusercontent.com/assets/1500684/14893469/c9d9a9c8-0d2c-11e6-8780-e020292357a7.png">

Firefox:

<img width="228" alt="firefox" src="https://cloud.githubusercontent.com/assets/1500684/14893473/cd797acc-0d2c-11e6-883f-b99c0633619c.png">

The relevant JS code is [here](https://github.com/javascriptair/site/blob/4a8b5bedc7a9c9af70923e5d9511b90b5fc754ea/src/pages/home/sections/episodes/episode/calendar.js#L72-L81) and [here](https://github.com/javascriptair/site/blob/4a8b5bedc7a9c9af70923e5d9511b90b5fc754ea/resources/css/episode.css#L270-L304) and [here](https://github.com/javascriptair/site/blob/4a8b5bedc7a9c9af70923e5d9511b90b5fc754ea/resources/css/episode.css#L339-L341) is the relevant CSS (not yet ported to aphrodite).

My guess is it's a rendering bug with Chrome. If anyone could figure out what we need to get around it that'd be sweet. Thanks!

**Comment by panzerdp** [comment]
Hello @kentcdodds 

I installed the site and made a build. However the calendar is displayed well for me (Chromium 49, Ubuntu).
Could it be a cache issue or some Chrome extension is breaking things? (Take a try in incognito).

![selection_002](https://cloud.githubusercontent.com/assets/1078719/14894982/115aa69c-0d7f-11e6-849f-aad2a7bbf06d.png)

Thanks.

**Comment by kentcdodds** [comment]
Hi @panzerdp! Thanks for giving it a look!

Could be a Mac only issue then. Also, the icon is really small because I mistakenly pushed some bad css :-)

Thanks for giving it a look. Maybe someone with a Windows could let us know if it's a problem on Windows or not.
