### ISSUE TITLE
Suggest changing the heading to "The Science of Learning Technical Content"

### ISSUE THREAD

**Issue by omoju** [javascriptair/site#95]
While I love the writeup you've put on the site, I would rather we focus on the "science", what we know about how people learn, and what implications that has on technical communities. Perhaps the heading could be "**The Science of Learning Technical Content**"

Even though we are going to speak about inclusion, we don't need to lead with it. This way we will get a broader spectrum of people willing to listen.
- related #74

**Comment by kentcdodds** [comment]
Hi @omoju,
Thank you for the suggestion. I agree that "diversity" and "inclusion" have (unfortunately) become pretty polarizing terms (as you've told me previously) and it'd be great to encourage more people to join with open minds by not focusing on those terms but instead focus on the science/research/data aspect of things. So I like the science bit.

I'm not certain that "Learning Technical Content" connotates exactly what I'm trying to go for with the show. What if it were: "The Science of People in Tech" ? That may align more closely. What do you think?

**Comment by omoju** [comment]
The **science of people in tech** sounds lovely. Lets go with that.

Btw, @kentcdodds am going to steal that moving forward and attribute it to you.
