### ISSUE TITLE
Randomize Guests and Contributors Order?

### ISSUE THREAD

**Issue by bookercodes** [javascriptair/site#96]
Hi :wave: 

[Product Hunt](https://www.producthunt.com/) randomize the order of their team members on the [about page](https://www.producthunt.com/about) (reload the page and you'll see).

If I remember correctly the idea was to show that all teammates are equal.

:white_check_mark: I think something similar would be nice for the [guests](https://javascriptair.com/guests/) and [contributors](https://javascriptair.com/contributors/) pages (sponsors should remain in the same order)

:x: It probably isn't a good idea for episode cards because they should be consistent across Twitter etc.

Of course this is low priorty but I think it could be a nice touch someday :smile: 

What do you think?

**Comment by kentcdodds** [comment]
Thanks for the suggestion @alexbooker! I think I'd be good with this. Right now most people on the site are sorted by twitter handle (or name if there is none) ([like so](https://github.com/javascriptair/site/blob/c74e061e817d3140e52c49079a6c6bb2728172d6/src/utils/utils.js#L87-L93)).

As this is generated at build-time, it would only be randomized every time the build happens, not on page refresh like you mention they do on Product Hunt (by the way, I tried and it's not randomizing for me ¯\_(ツ)_/¯). But we could definitely randomize for every build. I think that you're right that we should keep the show guests consistent. But I see no reason to not randomize the [panelists](https://github.com/javascriptair/site/blob/c74e061e817d3140e52c49079a6c6bb2728172d6/resources/panelists/index.js#L3-L12) and the [contributors](https://github.com/javascriptair/site/blob/6dc8c12b9f4a0c65f256ac04246af46a94712173/generate/contributors.js#L31) and [guests](https://github.com/javascriptair/site/blob/c74e061e817d3140e52c49079a6c6bb2728172d6/generate/guests.js#L10-L16) pages.

Definitely willing to accept a pull request to do this. I suggest a `randomize` function be added to [`utils`](https://github.com/javascriptair/site/blob/c74e061e817d3140e52c49079a6c6bb2728172d6/src/utils/utils.js) and use that.

**Comment by timarney** [comment]
@kentcdodds I can take a look at this.  Thinking shuffle from lodash will do the trick.  

For contributors, would that be 

```
nonFinancialContributors = [host, ...panelistContributors, ...contributors]
```

or should it exclude the host and panelist?

**Comment by kentcdodds** [comment]
Let's shuffle everything :-) Thanks!
